.angular-cli.json
karma.conf.js
package-lock.json
package.json
polyfills.ts
src/spec/action.spec.ts
test.ts
tsconfig.json
tsconfig.spec.json

This PR updates ngxs to use angular-cli to run unit tests

WIP: chore/unit-test-setup

---

.angular-cli.json
.editorconfig
src/spec/action.spec.ts
src/spec/mutation.spec.ts
tsconfig.json
tsconfig.spec.json

update some tsconfigs and adds a sample unit test

chore(testing): sample-test

---

src/spec/mutation.spec.ts

chore(testing): fix-test

---

README.md

chore: remove Injectable from the README

---

tsconfig.json
tsconfig.spec.json

Some may have noticed IDE issues with the unit tests. This should fix that.

chore(config): tsconfig

---

package.json
tsconfig.app.json

fix demo app build and create a test build when running ci

chore(integration): ci

---

.commitlintrc.json
.huskyrc.json
.lintstagedrc.json
.prettierrc.json
docs/contributing.md
package-lock.json
package.json

chore: refactor tooling

---

docs/concepts/select.md
src/select.ts
src/spec/select.spec.ts

adds ability to allow the Select decorator to accept a store class as the selector. closes #61

feature/store-select: use store class to select

---

src/ngxs.ts
src/plugins/localstorage/localstorage.module.ts
src/plugins/localstorage/localstorage.plugin.spec.ts

Adds a unit test for localstorage plugin and fixes one issue found.

chore/localstorage-test: add unit test for localstorage plugin

---

docs/plugins/localstorage.md

docs(plugins): fix LocalStoragePlugin options

---

docs/plugins/logger.md

Docs : rename option
Change expanded option to collapsed

Docs(Plugins logger) : change expanded option

---

src/symbols.ts

use typescript "Partial" type for patchState method

chore(core): patch state should be partial

---

docs/concepts/select.md
docs/concepts/state.md

Fixed some import issues in the docs.

fix(docs): updated bad or missing imports

---

src/plugins/logger/logger.plugin.ts

Fixes https://github.com/amcdnl/ngxs/issues/110

NgxsLoggerPlugin - log action payload if present

---

.circleci/config.yml
docs/advanced/cache.md
docs/advanced/pubsub.md
docs/concepts/select.md
docs/concepts/state.md
docs/concepts/store.md
docs/introduction/installation.md
docs/plugins/README.md
docs/plugins/devtools.md
docs/plugins/localstorage.md
docs/plugins/logger.md
integration/app/app.component.ts
integration/app/app.module.ts
integration/app/detail/detail.module.ts
integration/app/detail/detail.state.ts
integration/app/list/list.component.ts
integration/app/list/list.module.ts
integration/app/list/list.state.ts
integration/app/todo.state.ts
package.json
src/spec/module.spec.ts
tsconfig.app.json
tsconfig.json

Renames all imports and all documentation to the new package name

feat: rename to @ngxs/store

---

README.md

Update the fury badge to new npm package

chore(docs): Update README.md fury badge

---

packages/devtools-plugin/src/devtools.plugin.ts
packages/logger-plugin/src/logger.plugin.ts
packages/store/src/store.ts

fix: dispatches firing twice

---

packages/store/src/store.ts

fix(plugins): fix devtools

---

packages/storage-plugin/src/storage.plugin.ts
packages/store/src/actions.ts
packages/store/src/actions/init.ts
packages/store/src/module.ts
packages/store/src/plugin_api.ts

Fixes lazy loaded storages not populating on first load. closes #122

fix(storage): fix lazy loaded storage

---

integration/app/list/list.component.ts
integration/app/list/list.state.ts
packages/store/src/selector.ts

fix(store): ensure metadata exists for a Selector

---

docs/concepts/store.md

no need to re-listen to the observable

use withLatestFrom instead of map

---

docs/SUMMARY.md
docs/advanced/cancelation.md

addresses cancellation question in #143

chore(docs): cancellations

---

packages/store/src/action.ts
packages/store/src/of-action.ts
packages/store/src/state-factory.ts
packages/store/src/store.ts
packages/store/src/symbols.ts
packages/store/tests/dispatch.spec.ts

Adds ability to make actions cancellable.

feat: cancellable actions

---

packages/store/src/action.ts

Revert "fix(store): only add type if none exists"

---

packages/store/src/action.ts
packages/store/src/internals.ts
packages/store/tests/action.spec.ts
packages/store/tests/dispatch.spec.ts
packages/store/tests/state.spec.ts

Revert "fix(store): always set action type"

---

integration/app/app.component.spec.ts
integration/app/todo.state.ts
packages/devtools-plugin/src/devtools.plugin.ts
packages/logger-plugin/src/logger.plugin.ts
packages/storage-plugin/src/storage.plugin.ts
packages/storage-plugin/tests/storage.plugin.spec.ts
packages/store/src/action.ts
packages/store/src/public_api.ts
packages/store/src/state-factory.ts
packages/store/src/symbols.ts
packages/store/src/utils.ts
packages/store/tests/action.spec.ts
packages/store/tests/dispatch.spec.ts
packages/store/tests/select.spec.ts
packages/store/tests/state.spec.ts
packages/store/tests/store.spec.ts

This PR reverts type inference and requires a static type to bed set.
@amcdnl I think you should try this out locally first and see what you think. and see if it fixes the issues you started seeing in some of the plugins.
We should talk about this just wanted to get some code up so there was something concrete

WIP feat(store): require static type

---

packages/websocket-plugin/src/websocket-subject.ts

hold on to this till I submit another PR with unit tests.

fixed send error when socket is undefined

---

docs/advanced/action-handlers.md
docs/advanced/faq.md
docs/advanced/life-cycle.md
docs/community/news.md
docs/community/sponsors.md
docs/plugins/form.md
docs/plugins/websocket.md

chore: docs

---

packages/store/src/state-factory.ts
packages/store/tests/dispatch.spec.ts

Added primary tests to test the observable returned by the dispatch method.
Reproduced both reported issues with tests.
Fixed the issues.

Fix dispatch observable issues (fixes #233)

---

CHANGELOG.md
packages/devtools-plugin/src/devtools.module.ts

fix(devtools): options not updating 238

---

package-lock.json
package.json
packages/devtools-plugin/package.json
packages/form-plugin/package.json
packages/logger-plugin/package.json
packages/storage-plugin/package.json
packages/store/package.json
packages/websocket-plugin/package.json
packages/websocket-plugin/tests/websocket.module.spec.ts
tools/set-metadata.ts
tools/utils.ts
yarn.lock

- Fix lint issue
- Fix test issue
- Loosen deps

Websocket Tests

---

CHANGELOG.md
packages/store/src/actions-stream.ts
packages/store/src/module.ts
packages/store/src/store.ts

Moves action stream to internal usage.

fix: action stream exposition

---

packages/store/src/actions-stream.ts
packages/websocket-plugin/src/websocket-subject.ts
tslint.json

Addressing #248
- Fixed bad rxjs imports
- Blacklisted this import style in tsconfig to prevent this in the future.

fix: removed rxjs imports that bring in full library

---

docs/plugins/storage.md

chore(docs): update storage.md

---

packages/store/src/of-action.ts

fix(store): fix OpteratorFunction import

---

packages/store/src/state.ts
packages/store/tests/state.spec.ts

fix(store): ensure store names are valid

---

packages/store/src/public_api.ts
packages/store/src/state-factory.ts
packages/store/src/symbols.ts
packages/store/tests/state.spec.ts

feat(store): add life cycle interface and test

---

CONTRIBUTING.md
docs/README.md
docs/advanced/action-handlers.md
docs/advanced/cancellation.md
docs/advanced/composition.md
docs/advanced/errors.md
docs/advanced/faq.md
docs/advanced/lazy.md
docs/advanced/life-cycle.md
docs/advanced/meta-reducer.md
docs/advanced/shared-state.md
docs/advanced/sub-states.md
docs/concepts/actions.md
docs/concepts/select.md
docs/concepts/state.md
docs/concepts/store.md
docs/introduction/installation.md
docs/introduction/why.md
docs/plugins/devtools.md
docs/plugins/form.md
docs/plugins/intro.md
docs/plugins/logger.md
docs/plugins/storage.md
docs/plugins/websocket.md
docs/recipes/authentication.md
docs/recipes/cache.md
docs/recipes/unit-testing.md

Fix various documentation issues:
- Spelling mistakes
- Grammar problems

Fixes Documentation Issues (#318)

---

docs/README.md

A really small thing... Hopefully also can be a place for me to getting started :)

[Documentation] fix contributor link in README.md

---

docs/advanced/life-cycle.md

typo extends => implements

---

package-lock.json
packages/store/src/internals.ts
packages/store/src/module.ts
packages/store/src/state-factory.ts
packages/store/tests/helpers/counter.state.ts
packages/store/tests/helpers/simple.state.ts
packages/store/tests/helpers/todo.state.ts
packages/store/tests/lazy-load.spec.ts
packages/store/tests/select.spec.ts
packages/websocket-plugin/src/websocket-subject.ts
yarn.lock

I want to simplify store init and modules. this is the first step to ensuring nothing breaks when that happens

 chore(store): add lazy loading unit tests

---

docs/concepts/actions.md

chore: update docs

---

packages/store/src/module.ts
packages/store/src/state-factory.ts
packages/store/tests/dispatch.spec.ts

- Fix actions being dispatched multiple times
- Remove unused variables
- enhance tests

fix(store): only wire action onces

---

packages/store/src/actions-stream.ts
packages/store/src/dispatcher.ts
packages/store/src/state-factory.ts
packages/store/tests/dispatch.spec.ts

- Adds test for global error handling
- Implements errors handling

fix(errors): Global error handling works again

---

packages/logger-plugin/src/logger.module.ts
packages/logger-plugin/src/logger.plugin.ts
packages/logger-plugin/src/symbols.ts

Adds ability to disable logger and fixes options passing not working.

feat(logger): add disable state

---

packages/devtools-plugin/package.json
packages/form-plugin/package.json
packages/logger-plugin/package.json
packages/router-plugin/package.json
packages/storage-plugin/package.json
packages/store/package.json
packages/websocket-plugin/package.json

This fixes packaging not working with router in prod mode.
Reference: https://github.com/angular/angular-cli/issues/10584#issuecomment-386096327

fix(packaging): fix prod mode not working

---

docs/concepts/state.md

Missing reference to ctx in example

Fix typo in state.md

---

docs/community/projects.md

This project may be of interest to the ngxs community. It has just been updated to use ngxs 3, and consequently Angular 6 and RxJS 6. I use it every day for all CLI activity.

Added El Terminador, an Electron-based Terminal Manager

---

CHANGELOG.md
packages/store/src/selector.ts
packages/store/src/store.ts
packages/store/tests/selector.spec.ts

Adds support for multiple selects #51

feat(selector): add multi select support

---

packages/store/src/dispatcher.ts
packages/store/tests/action.spec.ts
packages/store/tests/dispatch.spec.ts
packages/store/tests/helpers/utils.ts

fix: dispatcher observable should propagate error

---

docs/concepts/store.md

There was an error, importing an action and declaring in same module.

Error in AddAnimal action in first example

---

packages/store/src/store.ts
packages/store/tests/store.spec.ts

Adds ability to pass a state class to a snapshot.

fix(store): fix snapshot signature

---

CHANGELOG.md
docs/plugins/storage.md
packages/storage-plugin/src/storage.plugin.ts
packages/storage-plugin/src/symbols.ts
packages/storage-plugin/tests/storage.plugin.spec.ts

Adds the ability to migrate data.

feat(storage): migrations

---

CHANGELOG.md
docs/concepts/select.md
packages/store/src/selector.ts
packages/store/tests/selector.spec.ts

Adds ability for meta selectors. Addresses #386

feat(selector): adds meta selectors

---

docs/concepts/select.md

fixed some stuff I stumbled over when reading

doc(concept/select): small fixes

---

CHANGELOG.md
package-lock.json
packages/devtools-plugin/src/devtools.plugin.ts
packages/store/src/store.ts

Adds ability to reset the store. This is used by devtools and useful for unit testing.

feat(store): store reset function

---

packages/logger-plugin/src/logger.module.ts
packages/logger-plugin/src/symbols.ts

made loggerOptionFactory to use custom options
no breaking changes. Fix for issue #373

fix(logger): fix logger not using custom options

---

packages/store/src/store.ts

Fixes subscribe and selects not entering the zone again.

fix(zone): fix subscribe enter zone

---

docs/concepts/state.md

Add missing parenthesis in example code.

docs: fix example code

---

packages/store/src/dispatcher.ts

add shareReplay operator to compose function
fix for issue #374

fix(dispatcher): fix subscription firing twice

---

packages/router-plugin/src/serializer.ts

Fixes freeze causing issues with router plugin.

fix(router): remove component from route due to freeze issues

---

docs/community/projects.md

Submitting project that supports the following blog post: [State Management In Angular using NGXS – Part 2](https://www.hsd.com.au/blog/state-management-in-angular-using-ngxs-part-2/)

Added Ngxs effects link

---

packages/store/src/actions-stream.ts
packages/websocket-plugin/src/websocket-handler.ts

fix: action stream should return in Angular zone

---

packages/store/src/utils/utils.ts
packages/store/tests/utils/utils.spec.ts

fix: state not set correctly when duplicate key in path

---

packages/router-plugin/index.ts

feat: expose serializer classes in @ngxs/router-plugin

---

docs/concepts/state.md

fix(state.md): fix typo

---

docs/plugins/logger.md

Add the `disabled` option to the list of available options for LoggerPluginModule.

doc: Update logger.md to include `disabled` option.

---

docs/advanced/sub-states.md

fix(sub-states.md): fix type

---

docs/advanced/errors.md

This PR improves the wording slightly to make the explanation a little more clear.

fix(errors.md): clean up sentence

---

docs/advanced/life-cycle.md

This PR rewords the opening paragraph slightly to make it a little more explicit (and avoid confusion).

fix(life-cycle.md): reword sentence

---

docs/plugins/intro.md

This PR updates the wording slightly to make it a bit more explicit and avoid possible confusion.

feat(intro.md): update wording

---

packages/store/src/internals.ts
packages/store/src/public_api.ts
packages/store/src/state-base.ts
packages/store/src/state-factory.ts

- After #485 those changes became unnecessary

fix(entity-base): cleanup changes in the store

---

packages/websocket-plugin/index.ts

Doing PR first time. Please check and then merge.

fixed issue #503

---

packages/devtools-plugin/src/devtools.plugin.ts

Importing an exported state json file was not implemented yet (see #416).
When importing a file in the redux devtools an action of type 'IMPORT_STATE' is dispatched which is now handled by the devtools-plugin with these steps:
* reset the devtools extension to the first state found in the imported data
* replay every action but the first (this is done during reset)
* reset the ngxs store to the current state with regards to the exported jump position

fix(devtools-plugin): implement state.json import

---

docs/concepts/select.md

docs: add section for dynamic selectors

---

CHANGELOG.md

Add links to the corresponding PR.

docs: changelog.md add links

---

docs/plugins/devtools.md

Saw this was missing, when looking into the docs for issue #525

docs(devtools): Added name option to devtools.md

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

```
[ ] Bugfix
[ ] Feature
```
Template for pull requests does not exist
Add template for pull requests 
```
[ ] Yes
[x] No
```

docs: add pull request template

---

docs/plugins/router.md

```
[ X] Bugfix
[ ] Feature
```
Correct state name from "route" to "router" 
```
[ ] Yes
[X ] No
```

Correct state name from "route" to "router"

---

integration/app/app.component.spec.ts
integration/app/app.module.ts

Added NgxsStoragePluginModule to integration example app.

feat(integration): add storage plugin to integration example

---

packages/storage-plugin/src/storage.plugin.ts

```
[x] Bugfix
```
Issue Number: #536 
It now checks for `val !== typeof 'undefined'` instead of `val !== 'undefined'`
```
[x] No
```

fix(storage-plugin): undefined check should be typeof 'undefined'

---

docs/advanced/meta-reducer.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(docs): syntax error in meta-reducer

---

docs/plugins/router.md

Add an example of implementing custom router state serializer.
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs(router): router state serializer

---

docs/concepts/select.md

```
[ ] Bugfix
[ ] Feature
```

docs: small cleanup of selector docs

---

docs/advanced/life-cycle.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
Related #375
Related #539

docs(store): feature modules order of imports

---

docs/plugins/devtools.md

change --save to --save-dev
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

@ngxs/devtools-plugin should be as dev dependence

---

docs/concepts/state.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs(state): complete async action dispatch example

---

docs/community/projects.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

Add link to reactive programming with observables & ngxs

---

docs/README.md

I thought this might be a usefull addition to the docs home.
```
[ ] Bugfix
[ ] Feature
```

docs(readme.md): added "Need Help?"

---

packages/store/src/utils/utils.ts

Functions SetValue can accept path that contain array
```
[ ] Bugfix
[x] Feature
```
Issue Number: [581](https://github.com/ngxs/store/issues/581)
```
[ ] Yes
[x] No
```

feat(form-plugin): path to state can contain array

---

CHANGELOG.md

```
[ ] Bugfix
[ ] Feature
```

docs: add information about cli in CHANGELOG.md

---

docs/plugins/intro.md

- [x ] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
- [ x] Tests for the changes have been added (for bug fixes / features)
- [x ] Docs have been added / updated (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
[x ] Code style update (formatting, local variables)
[ x] Documentation content changes
[ x] Other... Please describe: typos
```
```
[ ] Yes
[x ] No
```

chore(docs):Fixed typos in doc/plugin

---

docs/ngxs-labs/emitter.md

```
[ ] Bugfix
[ ] Feature
```

docs: fix typo in ngxs-labs readme

---

docs/ngxs-labs/emitter.md

```
[ ] Bugfix
[ ] Feature
```

docs: add info about emitting multiple value

---

docs/community/projects.md

```
[ ] Bugfix
[ ] Feature
```
Add a new link to the project section in the docs.
```
[ ] Yes
[x] No
```

docs(projects): add a link to a port of ngrx example app

---

tools/set-metadata.ts

```
[ ] Bugfix
[ ] Feature
```
Issue Number: #636
```
[ ] Yes
[x] No
```

fix(build): package peer dependencies

---

docs/community/projects.md

This PR adds a project to the resources section in the docs page.
```
[ ] Bugfix
[ ] Feature
[ x ] Documentation content changes
```
```
[ ] Yes
[ x ] No
```

docs(store) Add a project to the resources in the docs

---

integration/app/app.component.spec.ts
integration/app/app.component.ts
integration/app/list/list.component.ts
package.json
packages/form-plugin/src/directive.ts
packages/form-plugin/src/form.plugin.ts
packages/form-plugin/tests/form.plugin.spec.ts
packages/router-plugin/tests/router.plugin.spec.ts
packages/storage-plugin/tests/storage.plugin.spec.ts
packages/store/src/internal/state-operations.ts
packages/store/src/operators/of-action.ts
packages/store/src/utils/utils.ts
packages/store/tests/action.spec.ts
packages/store/tests/dispatch.spec.ts
packages/store/tests/store.spec.ts
packages/websocket-plugin/tests/websocket.module.spec.ts
yarn.lock

```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
The format script is not correct so some of the project files weren't formatted correctly with prettier, which cause unnecessary changes in pull requests, such as #649.
1. Prettier been upgraded because of some issues (ie https://github.com/prettier/prettier/pull/5188).
2. The NPM script has been fixed.
3. Format all unformatted files.
```
[ ] Yes
[x] No
```

style(prettier): fix format of project files

---

docs/recipes/authentication.md

fix ref to payload{}
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

docs: fix typo

---

docs/ngxs-labs/emitter.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ x] No
```

docs:(ngxs-labs-emitter) debugging typo

---

packages/storage-plugin/src/storage.plugin.ts
packages/storage-plugin/tests/storage.plugin.spec.ts

```
[X] Bugfix
[ ] Feature
```
Issue Number: #670
The handling of an 'undefined' string value is added again.
```
[ ] Yes
[X] No
```

Fix issue 670 - handling of 'undefined' by storage plugin

---

docs/recipes/unit-testing.md

```
[ ] Bugfix
[ ] Feature
```
There are no guidelines on how to test selectors created dynamically.
Created a new small section in the docs to show how to test dynamic selectors.
```
[ ] Yes
[x] No
```

docs: added how to test createSelector functions

---

docs/community/projects.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs(resources): add video tutorials

---

CHANGELOG.md
docs/SUMMARY.md
docs/ngxs-labs/dispatch-decorator.md
docs/ngxs-labs/emitter.md
docs/ngxs-labs/immer-adapter.md
docs/ngxs-labs/intro.md

```
[ ] Bugfix
[ ] Feature
```

docs(ngxs-labs): add new projects

---

packages/store/src/internal/state-operations.ts

```
[ ] Bugfix
[x] Feature
```
https://github.com/ngxs/store/issues/622
```
[ ] Yes
[x] No
```
Motivation to enable debug mode

feat(store): add recommendation for enable development mode

---

docs/advanced/action-handlers.md
packages/store/src/actions-stream.ts
packages/store/src/internal/state-factory.ts
packages/store/src/operators/of-action.ts
packages/store/tests/action.spec.ts

```
[ ] Bugfix
[x] Feature
```
Issue Number: https://github.com/ngxs/store/issues/710
https://github.com/ngxs/store/issues/518
* `ofActionCompleted`: triggers when an action has been completed whether it was successful or not
```
[ ] Yes
[x] No
```

feat(of-action): implement ofActionCompleted

---

tsconfig.json

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(integration): fix path finding in VSCode

---

karma.conf.js
package.json
yarn.lock

```
[ ] Bugfix
[ ] Feature
```
Issue Number: https://github.com/ngxs/store/issues/685
When we run `npm run test:ci` the browser is still running, and there should be a headless mode
```
[ ] Yes
[x] No
```

ci: enable headless chrome for correct work on CI

---

package.json
tools/package.ts
tools/utils.ts

```
[ ] Bugfix
[ ] Feature
```
no incremental build possible
```
$ yarn build:packages # build
$ yarn build:packages --watch # incremental build packages[0] - first on list
$ yarn build:packages --watch --package hmr-plugin # incremental build hmr-plugin
```
```
[ ] Yes
[x] No
```

feat(build): add watch mode for incremental build

---

packages/store/src/public_api.ts

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

chore(store): expose ActionCompletion

---

docs/advanced/composition.md
packages/store/src/decorators/state.ts
packages/store/src/internal/internals.ts
packages/store/src/symbols.ts
packages/store/src/utils/store-validators.ts
packages/store/tests/inheritance.spec.ts
packages/store/tests/state.spec.ts

```
[ ] Bugfix
[x] Feature
```
https://github.com/ngxs/store/issues/574
```ts
@State({
name: 'a',
defaults: { value: 'a' }
})
class MyState {}
@State<MyStateModel>({
name: 'b'
})
class MyOtherState extends MyState {} // can provide defaults: { value: 'a' }
```
```
[ ] Yes
[x] No
```

feat(store): inheritance state options

---

packages/store/src/operators/of-action.ts

```
[x] Bugfix
[ ] Feature
```
```typescript
export interface ActionCompletion<T = any> {
action: T;
result: {
successful: boolean;
canceled: boolean;
error?: Error;
};
}
```
The most common use case for the ofActionCompleted is to handle an HttpErrorResponse from the backend.
No need to use hacks like:
```typescript
const {
error: { message }
} = result.error as any;
```
```
[ ] Yes
[x] No
```

fix(store): action completion error type

---

.vscode/settings.json
docs/advanced/life-cycle.md
integration/app/list/list.state.ts
integration/app/store/todos/todo/todo.state.ts
integration/tests-ssr/todo.mocha.ts
packages/store/src/internal/bootstrapper.ts
packages/store/src/internal/internals.ts
packages/store/src/internal/lifecycle-state-manager.ts
packages/store/src/internal/state-factory.ts
packages/store/src/internal/state-operations.ts
packages/store/src/module.ts
packages/store/src/public_api.ts
packages/store/src/symbols.ts
packages/store/tests/state.spec.ts

https://github.com/ngxs/store/issues/547
https://github.com/ngxs/store/issues/749
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

feat(store): implement `ngxsAfterBootstrap` lifecycle hook

---

docs/advanced/life-cycle.md
packages/store/src/internal/lifecycle-state-manager.ts
packages/store/src/module.ts

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

chore(store): fix mistake in the `bootstrap` word

---

.vscode/settings.json
packages/store/src/actions-stream.ts
packages/store/src/internal/dispatcher.ts
packages/store/src/operators/wrap.ts
packages/store/src/operators/zone.ts
packages/store/src/store.ts
packages/store/tests/zone.spec.ts

```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
```
[ ] Yes
[x] No
```

refactor(store): re-implement `wrap` operator

---

docs/concepts/select.md

```
[ ] Bugfix
[ ] Feature
```
#762 
```
[ ] Yes
[x] No
```

docs(store): add info about using lambdas in static methods

---

packages/form-plugin/src/directive.ts
packages/form-plugin/src/form.plugin.ts
packages/form-plugin/src/internals.ts
packages/form-plugin/tests/form.plugin.spec.ts
tsconfig.json

```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
```
[ ] Yes
[x] No
```

refactor(form-plugin): remove duplicate code + add tests

---

docs/concepts/select.md

```
[ ] Bugfix
[ ] Feature
```
Issue Number: #762 
Other PR: #766 
Improved grammar issues, moved to new section at the bottom because it pertains to all selectors that contain a lambda in the `return` statement, not just dynamic selectors and corrected alternative fix after some investigation.

docs(store): improve info about using lambdas in static methods

---

packages/store/src/decorators/action.ts
packages/store/src/symbols.ts

```
[ ] Bugfix
[ ] Feature
[ x] Other... Please describe:
```
Add updated types for Action
The Action decorator doesn't accept "any" anymore it accepts and ActionDef
```
[ ] Yes
[ x] No
```

chore(store): add typing for the Action decorator

---

packages/store/operators/src/iif.ts
packages/store/operators/src/internals.ts
packages/store/operators/src/public_api.ts
packages/store/operators/src/update-item.ts
packages/store/operators/src/utils.ts
packages/store/operators/tests/update-item.spec.ts

```
[ ] Bugfix
[x] Feature
```
Issue Number: #545 
```
[ ] Yes
[x] No
```

feat(store): implement updateItem operator

---

packages/store/operators/src/insert-item.ts
packages/store/operators/src/public_api.ts
packages/store/operators/src/utils.ts
packages/store/operators/tests/insert-item.spec.ts

```
[ ] Bugfix
[x] Feature
```
Issue Number: #545 
```
[ ] Yes
[x] No
```

feat(store): implement insertItem operator

---

packages/store/operators/src/compose.ts
packages/store/operators/src/public_api.ts
packages/store/operators/tests/compose.spec.ts

```
[ ] Bugfix
[x] Feature
```
Issue Number: #545 
```
[ ] Yes
[x] No
```

feat(store): implement compose operator

---

README.md

```
[ ] Bugfix
[ ] Feature
```
https://github.com/ngxs/store/issues/760
https://github.com/ngxs/store/issues/745
Example docs 
https://github.com/angular/angular-cli
```
[ ] Yes
[x] No
```

docs(store): improved style guide

---

docs/advanced/action-handlers.md

```
[ ] Bugfix
[ ] Feature
```
Fixing the docs.
Updated docs
```
[ ] Yes
[x] No
```

docs(store): update incorrect number of pipes

---

docs/community/projects.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs(projects): add articles section

---

docs/community/projects.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs(projects): add ngatlanta talk

---

packages/store/src/decorators/action.ts
packages/store/src/symbols.ts
packages/store/tests/action.spec.ts

Fix for #794
```
[x] Bugfix
[ ] Feature
```
Issue Number: #794
```
[ ] Yes
[x] No
```

fix(store): ease ActionDef signature

---

docs/concepts/actions.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

chore: fix typo in actions.md

---

packages/store/src/decorators/selector.ts
packages/store/tests/selector.spec.ts

```
[x] Bugfix
[ ] Feature
```
Issue Number: #816 
```
[ ] Yes
[x] No
```

fix(store): bind context to the selector function

---

docs/advanced/operators.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs(store): add docs for the `iif` operator

---

packages/store/src/decorators/select.ts
packages/store/src/internal/internals.ts
packages/store/tests/select.spec.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

perf(store): implement new function for removing dollar at the end

---

docs/advanced/action-handlers.md
docs/ngxs-labs/dispatch-decorator.md
docs/ngxs-labs/emitter.md
docs/ngxs-labs/immer-adapter.md
docs/plugins/cli.md

```
[ ] Bugfix
[ ] Feature
```
Also, fixed a typo and remove the number of available pipes in action handlers.
```
[ ] Yes
[x] No
```

docs: install commands consistency

---

packages/storage-plugin/tests/storage.plugin.spec.ts

```
[x] Bugfix
[ ] Feature
```
```bash
Spec 'NgxsStoragePlugin when blank values are returned from localstorage should use default data if the string 'undefined' retrieved from localstorage' has no expectations.
```
```
[ ] Yes
[x] No
```

test(storage): fix 'undefined' unit test

---

packages/hmr-plugin/src/actions/hmr-before-destroy.action.ts
packages/hmr-plugin/src/actions/hmr-init.action.ts

```
[x] Bugfix
[ ] Feature
```
After the commit, I tested again with the `@dev builds` but it works with typescript 2.*, so I leave this PR only for consistency with the other action types defined in the project.
Related PRs:
#644 
#765 
```
[ ] Yes
[x] No
```

fix(hmr): actions type consistency

---

CHANGELOG.md
packages/hmr-plugin/src/symbols.ts
packages/store/src/execution/dispatchOutsideZoneNgxsExecutionStrategy.ts
packages/store/tests/execution/dispatchOutsideZoneNgxsExecutionStrategy.spec.ts

```
[X] Bugfix
[ ] Feature
```
Issues running against Angular 5
Removed the types used that don't exist in Angular 5
```
[ ] Yes
[X] No
```

fix(store): remove type usages incompatible with Angular 5 and TS 2.7

---

docs/advanced/operators.md

It would be nice to add "Relevant Articles" to topics.
@markwhitfeld 's article is a great explanation and it talks also about using other immutable update libraries like `immer`.
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs: add relevant articles in operators

---

docs/community/projects.md

```
[ ] Bugfix
[ ] Feature
```

docs: add link for the `NGXS Facade` article

---

docs/community/projects.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs(projects): add migration from ngrx article

---

docs/advanced/operators.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs(operators): fix state property name

---

packages/store/src/internal/state-factory.ts
packages/store/src/module.ts
packages/store/tests/lazy-load-late-init.spec.ts

```
[x] Bugfix
[ ] Feature
```
https://github.com/ngxs/store/issues/883
```
[ ] Yes
[x] No
```

fix(store): duplication of deferred states

---

packages/store/src/utils/memoize.ts
packages/store/src/utils/selector-utils.ts
packages/store/tests/selector.spec.ts

```
[X] Bugfix
[ ] Feature
```
Issue Number: #890
The issue is fixed.
```
[ ] Yes
[X] No
```
This fixes a typings regression introduced in v3.4.0

fix(store): fix createSelector regression with overly constrained type

---

packages/store/src/actions/symbols.ts
packages/store/src/decorators/action.ts
packages/store/src/internal/internals.ts
packages/store/src/public_api.ts
packages/store/src/symbols.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(store): expose ActionType and ActionOptions interfaces

---

docs/plugins/websocket.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
I wanted also to add `reconnectInterval` and `reconnectAttempts` because I saw them in the `d.ts` file.
But then I've found the issue #384.

docs(websocket): add deserializer

---

packages/router-plugin/src/router.state.ts
packages/router-plugin/tests/router.plugin.spec.ts

```
[x] Bugfix
[ ] Feature
```
Issue Number: #922 
```
[ ] Yes
[x] No
```

fix(router-plugin): trigger navigation on the queryparams change

---

packages/store/src/plugin-manager.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

refactor(store): plugin-manager

---

package.json
yarn.lock

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

build: fix dependency warnings

---

docs/community/projects.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs(projects): add new article

---

packages/hmr-plugin/src/hmr-manager.ts

```
[x] Bugfix
[ ] Feature
```
https://github.com/ngxs/store/issues/999
Remove old styles after reload
```
[ ] Yes
[x] No
```

fix(hmr-plugin): remove old styles after reload

---

docs/recipes/authentication.md

```
[ ] Bugfix
[ ] Feature
```
https://github.com/ngxs/store/issues/935

docs: fix authentication.md

---

docs/recipes/authentication.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs: fixed typos and missing interface

---

docs/community/projects.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs(projects): add ngAir talk with Mark

---

docs/advanced/options.md

```
[ ] Bugfix
[ ] Feature
```

docs(store): add selectorOptions section

---

packages/store/src/plugin_api.ts

```
[ ] Bugfix
[ ] Feature
```

feat(store): expose StateClass for @ngxs/store/testing

---

integration/app/store/todos/todo/todo.state.ts
integration/app/store/todos/todos.state.ts
packages/hmr-plugin/src/internal/hmr-options-builder.ts
packages/router-plugin/src/router.state.ts
packages/storage-plugin/tests/storage.plugin.spec.ts
packages/store/src/execution/dispatch-outside-zone-ngxs-execution-strategy.ts
packages/store/src/internal/state-factory.ts
packages/store/src/modules/ngxs-feature.module.ts
packages/store/src/modules/ngxs-root.module.ts
packages/store/src/utils/selector-utils.ts
packages/store/src/utils/utils.ts
packages/store/tests/action.spec.ts
packages/store/tests/dev-mode.spec.ts
packages/store/tests/dispatch.spec.ts
packages/store/tests/execution/noop-ngxs-execution-strategy.spec.ts
packages/store/tests/helpers/simple.state.ts
packages/store/tests/helpers/utils.ts
packages/store/tests/selector.spec.ts
packages/store/tests/state.spec.ts
packages/websocket-plugin/src/symbols.ts
packages/websocket-plugin/src/websocket-handler.ts
packages/websocket-plugin/src/websocket-subject.ts
tsconfig.json

```
[ ] Bugfix
[ ] Feature
```
Remove  unused variables
```
[ ] Yes
[x] No
```

refactor: add noUnusedLocals and noUnusedParameters options

---

docs/plugins/storage.md
docs/recipes/style-guide.md

```
[ ] Bugfix
[ ] Feature
```
Property 'key' is missing in type 'StorageEngine' but required in type 'StorageEngine'.
Implemented
```
[ ] Yes
[x] No
```

docs: fix list key function in storage document

---

docs/plugins/router.md

```
[ ] Bugfix
[ ] Feature
```

feat(docs): add docs for the new action `RouterDataResolved`

---

packages/form-plugin/src/form.plugin.ts
packages/store/src/internal/internals.ts
packages/store/src/internal/state-factory.ts
packages/store/src/utils/utils.ts

```
[ ] Bugfix
[ ] Feature
```

perf: replace `spread` with `slice`

---

docs/concepts/select.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[X] No
```

docs: update `@Select` example in documentation

---

docs/ngxs-labs/intro.md

```
[ ] Bugfix
[ ] Feature
```

feat(docs): add `@ngxs-labs/select-snapshot` package to the docs

---

packages/router-plugin/src/router.actions.ts

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(router-plugin): add `RouterDataResolved` to union type

---

jest.config.js

```
[ ] Bugfix
[ ] Feature
```

fix: make jest collect coverage only on the CircleCI

---

integration/jest.integration.config.js
jest.config.js
package.json
packages/store/src/store.ts
packages/store/tests/selector.spec.ts

```
[x] Bugfix
[ ] Feature
```
Issue Number: https://github.com/ngxs/store/issues/843
```
[ ] Yes
[x] No
```

fix(store): correct error handling in selectors

---

.circleci/config.yml
.travis.yml

```
[ ] Bugfix
[ ] Feature
```
https://github.com/ngxs/store/pull/1097

ci: upgrade node.js in circle ci

---

docs/concepts/select.md
docs/concepts/state.md
docs/recipes/style-guide.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

docs: update

---

docs/community/projects.md

- [ X ] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
- [ X ] Docs have been added / updated (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ X ] No
```

docs: add project and slides from talk

---

docs/recipes/unit-testing.md

```
[ ] Bugfix
[ ] Feature
```
Issue Number: #833

docs(store): add info for testing async actions

---

packages/store/internals/src/object-utils.ts
packages/store/src/store.ts
packages/store/src/symbols.ts
packages/store/tests/utils/utils.spec.ts

```
[x] Bugfix
[ ] Feature
```
Issue Number: https://github.com/ngxs/store/issues/1126
```
[ ] Yes
[x] No
```

fix(store): does not properly restore state

---

packages/hmr-plugin/src/hmr-manager.ts
packages/hmr-plugin/src/tests/hmr-manager.spec.ts
packages/hmr-plugin/src/tests/hmr-mock.ts

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: add tests
```

test(hmr-plugin): coverage improvement for hmr plugin

---

packages/store/tests/state.spec.ts

```
[ ] Bugfix
[ ] Feature
```

test(store): expect when state parameters are not passed

---

packages/store/tests/state.spec.ts

test(store): improved coverage for simplePatch

---

packages/store/operators/src/compose.ts
packages/store/operators/tests/compose.spec.ts
packages/store/operators/tests/patch.spec.ts
packages/store/operators/tests/update-item.spec.ts
packages/store/types/tests/state-operators.compose.lint.ts

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Preparation for TS upgrade
```
The files do not compile against Typescript 3.4
The files will compile against Typescript 3.4
```
[ ] Yes
[X] No
```

chore: update files in preparation for Typescript 3.4 compatibility

---

docs/concepts/store.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs: fix destructuring

---

packages/store/tests/select.spec.ts

```
[ ] Bugfix
[ ] Feature
```
Issue Number: https://github.com/ngxs/store/issues/995

test(store): expect unsubscribe selection after unhandled error

---

docs/plugins/form.md

```
[ ] Bugfix
[ ] Feature
```
Currently, there are mentions about "pizzas" and "todos" in the state, that might be confusing.
```
[ ] Yes
[x] No
```

docs(form-plugin): remove inconsistent mix of "pizzas" and "todos"

---

packages/store/src/internal/state-factory.ts

```
[ ] Bugfix
[ ] Feature
```
Remove unnecessary piping via `map` operator.
```
[ ] Yes
[x] No
```

refactor: remove unnecessary piping via `map` operator

---

packages/router-plugin/tests/router.plugin.spec.ts
packages/router-plugin/tests/test-lazy.module.ts

refactor(router-plugin): remove extra file in tests

---

package.json
yarn.lock

```
[ ] Bugfix
[ ] Feature
```
Issue Number: #1165 
Angular 8.2 supports TS 3.5, [related PR](https://github.com/angular/angular/pull/31615)
```
[ ] Yes
[ ] No
```

build(typescript): upgrade to the v3.5

---

docs/advanced/errors.md

- [ X ] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
```
[ ] Bugfix
[ ] Feature
```
Issue Number:

docs: error handling

---

docs/advanced/errors.md

- [ X ] Docs have been added / updated (for bug fixes / features)
[ ] Bugfix
[ ] Feature

docs: revert change

---

packages/store/src/configs/messages.config.ts
packages/store/src/decorators/selector.ts
packages/store/src/internal/internals.ts
packages/store/tests/selector.spec.ts
packages/store/types/tests/selection.lint.ts

```
[ ] Bugfix
[ ] Feature
```

test(store): add unit and types tests for selector decorator

---

docs/plugins/form.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

docs(form-plugin): add missing state name

---

packages/form-plugin/src/actions.ts
packages/form-plugin/src/directive.ts
packages/form-plugin/src/symbols.ts
packages/form-plugin/tests/form.plugin.spec.ts

```
[x] Bugfix
[ ] Feature
```
Issue Number: #429 
```
[ ] Yes
[x] No
```

feat(form-plugin): reduce `UpdateFormStatus` action dispatching

---

docs/SUMMARY.md
docs/recipes/dynamic-plugins.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

docs(store): add information about dynamic plugins

---

packages/store/operators/src/patch.ts
packages/store/src/store.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

chore: prettier format

---

docs/SUMMARY.md
docs/recipes/debouncing-actions.md

```
[ ] Bugfix
[ ] Feature
```
Issue Number: #1225 
```
[ ] Yes
[ ] No
```
This PR improves the documentation with recipe that shows how to debounce actions and reduce the amount of requests send to the server.

docs: add `debouncing actions` recipe

---

docs/concepts/select.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
This PR improves the documentation with information about how to order selectors. This was originally described in the #1143 issue.

docs(store): enhance docs about the order of selectors

---

packages/storage-plugin/tests/storage.plugin.spec.ts

```
[ ] Bugfix
[ ] Feature
```
In the current behavior Jest doesn't run expectations inside `subscribe` block.
`select` is replaced with `selectSnapshot` and expectations are run successfully.
```
[ ] Yes
[x] No
```

test(storage-plugin): replace "select" with "selectSnapshot"

---

package.json
packages/store/types/tests/dispatch.lint.ts
yarn.lock

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

build(ci): fix dtslint type problem

---

.yarnrc

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

build(ci): ignore engines check when breaks install

---

docs/community/contributors.md

fix issue for displaying image in gitbook
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: --> fix in contributors.md to fix issue in gitbook 
```
Issue Number: #1284 
- svg image is displayed in GitHub & GitBook correct 
```
[ ] Yes
[x] No
```

docs: fix empty contributors list #1284

---

docs/concepts/select.md

docs(concepts->select): Correct typo fasion to fashion
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

Correct typo

---

docs/plugins/hmr.md

```
[ ] Bugfix
[ ] Feature
```
Issue Number: https://github.com/ngxs/store/issues/1233

docs(hmr-plugin): fix information about usage hmr plugin

---

packages/store/src/plugin-manager.ts

```
[ ] Bugfix
[ ] Feature
```

refactor(store): rename methods in register plugin

---

package.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

build(ci): throw error when use npm instead yarn

---

packages/devtools-plugin/tests/devtools-custom.spec.ts
packages/devtools-plugin/tests/devtools-errors.spec.ts
packages/devtools-plugin/tests/devtools.spec.ts
packages/devtools-plugin/tests/utils/create-devtools.ts
packages/devtools-plugin/tests/utils/redux-connector.ts
packages/devtools-plugin/tests/utils/symbols.ts

```
[ ] Bugfix
[ ] Feature
```
Emulate redux devtools
```
[ ] Yes
[x] No
```

test(devtools-plugins): improved coverage

---

docs/advanced/actions-life-cycle.md
docs/advanced/composition.md
docs/advanced/errors.md
docs/advanced/meta-reducer.md
docs/advanced/operators.md
docs/advanced/options.md
docs/community/contributing.md
docs/community/projects.md
docs/concepts/actions.md
docs/concepts/select.md
docs/concepts/state.md
docs/concepts/store.md
docs/recipes/unit-testing.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs: fix formatting and errors

---

docs/advanced/life-cycle.md

```
[ ] Bugfix
[ ] Feature
```
Issue Number: #1349 
```
[ ] Yes
[x] No
```

docs: enhance docs about using `APP_INITIALIZER` with NGXS

---

docs/concepts/actions.md

These updates reflect what the styleguide says about naming actions
```
[ ] Bugfix
[ ] Feature
```
Seemed as if these docs contradict the Style Guide
Updated Docs to follow the STyle Guide
```
[ ] Yes
[x] No
```

docs: update actions style guide

---

.codacy.yml

```
[ ] Bugfix
[ ] Feature
[X] CI related changes
```
Codacy complains about many things in our md files. It is pointless and distracting.
Ignore `*.md` files from the analysis.
```
[ ] Yes
[X] No
```

chore: configure codacy to ignore md files

---

packages/form-plugin/tests/form.plugin.spec.ts

```
[ ] Bugfix
[ ] Feature
```
Expectations are not being run inside the `subscribe` block :point_down: 
```
[ ] Yes
[x] No
```

test(form-plugin): replace `select` with `selectSnapshot`

---

docs/recipes/component-events-from-ngxs.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

docs: fix recipes example

---

packages/store/types/tests/dispatch.lint.ts

```
[ ] Bugfix
[ ] Feature
```

test(store): improvement test typings

---

packages/store/src/symbols.ts

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```

feat(store): improved typings for children states

---

packages/logger-plugin/tests/logger.plugin.spec.ts
packages/store/tests/execution/noop-ngxs-execution-strategy.spec.ts
tsconfig.json

```
[ ] Bugfix
[ ] Feature
```
Before now in unit tests you can import classes from anywhere
Exports from package scope `@ngxs/scope` will only work public
```
[ ] Yes
[x] No
```
We should not use such abbreviations here.
```
"@ngxs/*": ["packages/*/index.ts"],
```
Because the IDEA or VsCode will not correctly substitute imports.

build: expose only public API

---

packages/store/operators/src/append.ts
packages/store/operators/src/compose.ts
packages/store/operators/src/iif.ts
packages/store/operators/src/insert-item.ts
packages/store/operators/src/internals.ts
packages/store/operators/src/remove-item.ts
packages/store/types/tests/state-operator.lint.ts
packages/store/types/tests/state-operators.compose.lint.ts
packages/store/types/tests/state-operators.iif.lint.ts
packages/store/types/tsconfig.json

```
[x] Bugfix
[ ] Feature
```
Issue Number: https://github.com/ngxs/store/issues/1375
Operators must explicitly return their type
```
[ ] Yes
[x] No
```

fix(store): explicit typings for state operators

---

publication/announcement_template.md

```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Publications
```
```
[ ] Yes
[X] No
```

chore: add template for announcement posts

---

docs/ngxs-labs/intro.md

```
[ ] Bugfix
[ ] Feature
```
Added the new package to the `release` branch which is published to the docs for the current version release.

docs: add new actions-executing labs project to current docs branch

---

docs/recipes/authentication.md

Fix 66 line
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs: update authentication.md

---

docs/recipes/authentication.md

Fix 66 line
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

docs: update authentication.md (#1408)

---

bundlesize.config.json
docs/concepts/actions.md
docs/plugins/storage.md
docs/recipes/cache.md
publication/announcement_template.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

chore: prettier fix (yarn format)

---

.codacy.yml
.codeclimate.yml
.eslintrc.js
.prettierignore
cypress/support/index.js
package.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

chore: support yml, js format

---

docs/plugins/hmr.md
packages/hmr-plugin/src/hmr-bootstrap.ts
packages/hmr-plugin/src/symbols.ts
packages/hmr-plugin/src/tests/hmr-manager.spec.ts

Improvement to naming before committing to release of new API.
```
[X] Bugfix
[ ] Feature
```

refactor(hmr-plugin): rename persistAfterDestroy option to restorePreDestroySnapshot

---

packages/hmr-plugin/src/hmr-bootstrap.ts
packages/hmr-plugin/src/symbols.ts
packages/hmr-plugin/src/tests/hmr-manager.spec.ts

revert(hmr-plugin): remove invalid options and use valid tests

---

packages/hmr-plugin/src/tests/hmr-manager.spec.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

test(hmr-plugin): check mutate as side effect

---

packages/store/src/internal/internals.ts
packages/store/tests/ensure-store.spec.ts

```
[X] Bugfix
[ ] Feature
```
Removing a very dangerous property.

fix(store): the MetaDataModel for a store should never reference the instance

---

packages/store/src/internal/internals.ts
packages/store/src/internal/lifecycle-state-manager.ts
packages/store/src/internal/state-context-factory.ts
packages/store/src/internal/state-factory.ts

```
[ ] Bugfix
[ ] Feature
```
Improve variable naming to reduce confusion of concepts.

refactor: fix naming of usages of MappedStore

---

docs/SUMMARY.md
docs/advanced/mapped-sub-states.md
docs/advanced/sub-states.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

docs: mapped sub states

---

bundlesize.config.json

```
[ ] Bugfix
[ ] Feature
```

build: ngxs plugin bundle checking

---

integrations/ivy/angular.json
integrations/ivy/package.json
integrations/ivy/tsconfig.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

build(ivy): update to Angular 9 rc-1

---

docs/advanced/errors.md

```
[ ] Bugfix
[ ] Feature
```
Issue Number: https://github.com/ngxs/store/issues/995

docs: handling errors within an Select

---

docs/advanced/errors.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs: remove extra 'the' from errors.md

---

docs/community/projects.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs(projects): adding a new article in spanish

---

docs/recipes/style-guide.md

```
[ ] Bugfix
[ ] Feature
```
Issue Number: https://github.com/ngxs/store/issues/1331

docs: improved style guide

---

.lintstagedrc.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

style: apply prettier to all files on the `pre-commit` hook

---

publication/2019-10-21_announcing_ngxs_3_6/article.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

chore: update announcement article

---

docs/advanced/life-cycle.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

chore: update life-cycle.md

---

packages/store/types/tests/create-selector.lint.ts

```
[ ] Bugfix
[ ] Feature
```
Issue Number: https://github.com/ngxs/store/issues/913
```
[ ] Yes
[ ] No
```

test: add test for createSelector

---

docs/plugins/hmr.md
publication/2019-10-21_announcing_ngxs_3_6/article.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

chore: update HMR announce

---

packages/store/tests/utils/utils.spec.ts

```
[ ] Bugfix
[ ] Feature
```

test(store): add test for propGetter

---

docs/ngxs-labs/intro.md

```
[ ] Bugfix
[ ] Feature
```
Adding the attach-actions labs project to the docs. 
```
[ ] Yes
[x] No
```

docs: add attach-action as labs project

---

packages/router-plugin/package.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

build(router-plugin): provide UMD name of the external module

---

.travis.yml
.yarnrc
integrations/ivy/package.json
integrations/ivy/src/app/store-ivy.module.ts
integrations/ivy/yarn.lock

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

ci: workaround build failed for Travis CI

---

.travis.yml
.yarnrc

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

ci: disable cache for Travis CI

---

.yarnrc
packages/store/src/host-environment/host-environment.ts
packages/store/src/module.ts
packages/store/tests/config-validator.spec.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

refactor: correct usage host tokens

---

docs/community/projects.md

- [ x ] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
- [ x ] Tests for the changes have been added (for bug fixes / features)
- [ x ] Docs have been added / updated (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
[ x ] Documentation content changes
```
```
[ ] Yes
[ x ] No
```

docs(projects): adding a new project to the community project list

---

publication/2019-10-21_announcing_ngxs_3_6/article.md

```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Article
```

chore: prepare 3.6 release article

---

integrations/ivy/package.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

build: run sync ngcc

---

docs/advanced/token.md

@Selector() expects an array. Current preview does not work. Type error.
```
[ ] Bugfix
[ ] Feature
[x ] Documentation content changes
```
```
[ ] Yes
[x] No
```

Type error in example from documentation for State Token.

---

docs/advanced/token.md
docs/ngxs-labs/intro.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

docs: sync with master

---

bundlesize.config.json
packages/store/src/ivy/ivy-enabled-in-dev-mode.ts

```
[ ] Bugfix
[ ] Feature
```
Issue Number: https://github.com/ngxs/store/issues/1525
```
[ ] Yes
[x] No
```

fix(store): fix regression after upgrade to angular.rc-11

---

README.md
packages/store/README.md

```
[ ] Bugfix
[ ] Feature
```
Issue Number: https://github.com/ngxs/store/issues/1528

docs: fix links

---

docs/advanced/action-handlers.md

```
[ ] Bugfix
[ ] Feature
```
#1536 
```
[ ] Yes
[ ] No
```

docs: update example to provide service in the root injector

---

README.md
docs/README.md

```
[ ] Bugfix
[ ] Feature
```
Two new links are given to the Ivy migration guide, one from repo README, one from documentation front page.
```
[ ] Yes
[x] No
```

docs: add noticeable links to ivy migration guide

---

docs/recipes/debouncing-actions.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

@Injectable() added to top of the Class for IVY Support

---

docs/recipes/authentication.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

Angular9 @Injectable updates

---

docs/recipes/authentication.md
docs/recipes/cache.md
docs/recipes/debouncing-actions.md
docs/recipes/immutability-helpers.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

@Injectable() added to top of the Class for IVY Support (#1553)

---

docs/advanced/action-handlers.md

```
[ ] Bugfix
[ ] Feature
```
Action handler docs shows example of subscribing to actions and it may be unclear to new people wether they need to unsubscribe from the stream.
In this PR I improved action handler docs by adding a new example to remember people they need to unsubscrinbe from action streams.
```
[ ] Yes
[x] No
```

docs: added simple exmple on how to unsubscribe from action handlers

---

docs/advanced/lazy.md

```
[ ] Bugfix
[ ] Feature
```
Current text: `You register this state is some lazy-loaded module via...`
Fixed text: `You register this state in some lazy-loaded module via...`
```
[ ] Yes
[x] No
```

docs: typo fixed

---

docs/introduction/installation.md

```
[ ] Bugfix
[ ] Feature
```
Giving an example root module setup with the normal development mode setting from the environment will likely prevent a number of beginner errors for our users.
```
[ ] Yes
[x] No
```

docs: improve intro root module sample

---

docs/ngxs-labs/intro.md

- [ X ] Docs have been added / updated (for bug fixes / features)
No

docs(ngxs-labs): include firestore plugin

---

docs/recipes/unit-testing.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs: remove deprecated testbed.get

---

docs/recipes/unit-testing.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

docs: remove deprecated testbed.get (#1569)

---

bundlesize.config.json
docs/plugins/logger.md
packages/logger-plugin/src/logger.module.ts
packages/logger-plugin/src/logger.plugin.ts
packages/logger-plugin/src/symbols.ts
packages/logger-plugin/tests/logger.plugin.spec.ts
publication/announcing_ngxs_next/article.md

```
[ ] Bugfix
[x] Feature
```
Issue Number: #1565
Described in the docs.
```
[ ] Yes
[x] No
```

feat(logger-plugin): Action Filter in Logger Plugin

---

integration/app/detail/detail.state.ts
packages/devtools-plugin/tests/devtools-custom.spec.ts
packages/devtools-plugin/tests/devtools-errors.spec.ts
packages/devtools-plugin/tests/devtools.spec.ts
packages/form-plugin/tests/form.plugin.spec.ts
packages/hmr-plugin/src/tests/hmr-mock.ts
packages/router-plugin/tests/issues/issue-1407.spec.ts
packages/router-plugin/tests/router-data-resolved.spec.ts
packages/router-plugin/tests/router.plugin.spec.ts
packages/storage-plugin/tests/storage.plugin.spec.ts
packages/store/internals/testing/tests/ngxs.setup.spec.ts
packages/store/tests/action-handler.spec.ts
packages/store/tests/action.spec.ts
packages/store/tests/ensure-store.spec.ts
packages/store/tests/execution/dispatch-outside-zone-ngxs-execution-strategy.spec.ts
packages/store/tests/helpers/counter.state.ts
packages/store/tests/ngxs-onchanges.spec.ts
packages/store/tests/state.spec.ts
packages/store/tests/zone.spec.ts
packages/store/types/tests/state-token.lint.ts
publication/2019-12-11_announcing_ngxs_3_6/article.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

build: add the missing decorator before upgrading to Angular 9

---

docs/plugins/form.md

Update form.md to contain a FormFuilder example.
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

docs(form-plugin): update form.md

---

docs/plugins/form.md

Update form.md to contain a FormFuilder example.
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

Update form.md (#1581)

---

docs/plugins/form.md

Added an ngOnInit as well as the imports in order to help people who might not be as familiar.
```
[ ] Bugfix
[ ] Feature
```
Just adding some more information on the documentation. Although minor, it could help someone who is new to NGXS.
```
[ ] Yes
[X] No
```

docs(form-plugin): updated form.md

---

docs/plugins/storage.md
publication/announcing_ngxs_next/article.md

```
[ ] Bugfix
[ ] Feature
```

docs(storage-plugin): update changelog related to serialization interceptors

---

.circleci/config.yml
.travis.yml
integrations/hello-world-ng8/README.md
integrations/hello-world-ng8/angular.json
integrations/hello-world-ng8/package.json
integrations/hello-world-ng8/src/app/app.component.html
integrations/hello-world-ng8/src/app/app.component.ts
integrations/hello-world-ng8/src/app/app.module.ts
integrations/hello-world-ng8/src/app/app.state.ts
integrations/hello-world-ng8/src/app/store.module.ts
integrations/hello-world-ng8/src/environments/environment.prod.ts
integrations/hello-world-ng8/src/environments/environment.ts
integrations/hello-world-ng8/src/index.html
integrations/hello-world-ng8/src/main.ts
integrations/hello-world-ng8/src/polyfills.ts
integrations/hello-world-ng8/src/tsconfig.app.json
integrations/hello-world-ng8/tsconfig.json
package.json

```
[ ] Bugfix
[ ] Feature
```
@markwhitfeld Before we upgrade to Angular 9, we need a stable build of the application with Angular 8. Then we can update further this project to Angular Ivy! 
Angular (8.0.*) Compiler required TypeScript  >= 3.4 and <3.5
```
[ ] Yes
[x] No
```

build: add build integration test with Angular 8

---

docs/community/projects.md

* [ x ] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
* [ x ] Tests for the changes have been added (for bug fixes / features)
* [ x ] Docs have been added / updated (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
[ x ] Documentation content changes
```
```
[ ] Yes
[ x ] No
```

docs(projects): add a new community project

---

CHANGELOG.md
packages/logger-plugin/src/action-logger.ts
packages/logger-plugin/tests/helpers/index.ts
packages/logger-plugin/tests/helpers/setup-with-logger.ts
packages/logger-plugin/tests/helpers/setup.ts
packages/logger-plugin/tests/issues/issue-1551.spec.ts
packages/logger-plugin/tests/logger.plugin.spec.ts

```
[x] Bugfix
[ ] Feature
```
Issue Number: #1551 
```
[ ] Yes
[x] No
```

fix(logger-plugin): filter out only `undefined` payloads

---

docs/SUMMARY.md
docs/advanced/optimizing-selectors.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs(optimizing-selectors): create page

---

CHANGELOG.md
integration/main.server.ts
integration/server.ts
integration/tsconfig.app.json
integration/tsconfig.server.json
package.json
packages/store/operators/tests/update-item.spec.ts
yarn.lock

```
[ ] Bugfix
[ ] Feature
```
Issue Number: #1613 
```
[ ] Yes
[x] No
```

build: upgrade TS to 3.9 to ensure that no breaking changes get added

---

CHANGELOG.md
bundlesize.config.json
packages/store/src/internal/dispatcher.ts
packages/store/src/internal/internals.ts
packages/store/src/internal/state-factory.ts
packages/store/src/internal/state-operations.ts
packages/store/src/store.ts
packages/store/src/utils/utils.ts
packages/store/tests/issues/issue-1603-no-type-property-on-the-action.spec.ts
packages/store/tests/issues/issue-759-dispatching-empty.spec.ts

```
[ ] Bugfix
[x] Feature
```
Issue Number: #1603 
```
[ ] Yes
[x] No
```

feat: throw an error when actions do not have a static type property

---

CHANGELOG.md
packages/store/src/decorators/select/select.ts
packages/store/src/decorators/select/symbols.ts
packages/store/types/tests/selection.lint.ts
packages/store/types/tests/state-token.lint.ts

```
[ ] Bugfix
[ ] Feature
```
Issue Number: #1532 
```
[ ] Yes
[ ] No
```

fix(store): remove SelectType<T> implementation due to cannot assign @Select to private/protected property

---

docs/concepts/select.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

docs: add a side note about strict mode

---

.github/CODEOWNERS

```
[ ] Bugfix
[ ] Feature
```
https://tech.people-doc.com/using-github-codeowners-file.html
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners#example-of-a-codeowners-file

ci: set default reviewers

---

packages/devtools-plugin/package.json
packages/form-plugin/package.json
packages/hmr-plugin/package.json
packages/logger-plugin/package.json
packages/router-plugin/package.json
packages/storage-plugin/package.json
packages/store/package.json
packages/websocket-plugin/package.json

```
[ ] Bugfix
[ ] Feature
```
This is still the minimum PR to raise the version in peerDependencies

chore: bump angular version in peerDependencies

---

.circleci/config.yml
.travis.yml
package.json

```
[X ] CI related changes
```
```
[ X ] No
```
Rename step

chore: rename integration step

---

docs/plugins/hmr.md
packages/hmr-plugin/src/hmr-bootstrap.ts

```
```
Deprecation note for HMR plugin

docs(hmr): deprecation note

---

integrations/hello-world-ng7/angular.json
integrations/hello-world-ng7/jest.config.js
integrations/hello-world-ng7/package.json
integrations/hello-world-ng7/src/app/app.component.spec.ts
integrations/hello-world-ng7/src/browserslist
integrations/hello-world-ng7/src/environments/environment.ts
integrations/hello-world-ng7/src/jestGlobalMocks.ts
integrations/hello-world-ng7/src/karma.conf.js
integrations/hello-world-ng7/src/polyfills.ts
integrations/hello-world-ng7/src/setupJest.ts
integrations/hello-world-ng7/src/styles.sass
integrations/hello-world-ng7/src/tsconfig.app.json
integrations/hello-world-ng7/src/tsconfig.spec.json
integrations/hello-world-ng7/src/tslint.json
integrations/hello-world-ng7/tsconfig.app.json
integrations/hello-world-ng7/tsconfig.json
integrations/hello-world-ng7/tsconfig.spec.json
integrations/hello-world-ng7/tslint.json
integrations/hello-world-ng7/yarn.lock

```
[ ] Bugfix
[ ] Feature
[X] CI related changes
```
The tests were removed from the ng7 integration project to get it working in PR #1659.
That project was originally copied from a ng9 project, and therefore had all the wrong configuration for a true ng7 project.
Reset the basic ng7 project structure to a fresh template ng7 project with jest that I found on github.
Kept the tests and all other integration project code. Everything passes, including the jest tests :+1:.
```
[ ] Yes
[X] No …
```

test(integration): readd tests to ng7 integration project

---

docs/recipes/unit-testing.md

Fix DOC incorrect wording
```
[ ] Bugfix
[ ] Feature
[ x] Documentation content changes
```
```
[ ] Yes
[ x] No
```

docs: update unit-testing.md

---

README.md
docs/recipes/unit-testing.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[X] No
```

chore: merge release

---

docs/recipes/intregration-with-rxangular.md

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Documentation
```
```
[ ] Yes
[x] No
```

docs(recipe): Provide recipe for integration with RxAngular

---

docs/SUMMARY.md

```
[ ] Bugfix
[ ] Feature
```

docs(recipe): Add to SUMMARY.md RxAngular Recipe

---

packages/devtools-plugin/package.json
packages/form-plugin/package.json
packages/hmr-plugin/package.json
packages/logger-plugin/package.json
packages/router-plugin/package.json
packages/storage-plugin/package.json
packages/store/package.json
packages/websocket-plugin/package.json

```
[ ] Bugfix
[ ] Feature
```
Angular 11 is included in the supported dependency versions for all packages
```
[ ] Yes
[ ] No
```

chore: allow Angular 11 as dependency

---

package.json
yarn.lock

```
[ ] Bugfix
[ ] Feature
```
Lock the version of the cli and angular builder to match the Angular library version
```
[ ] Yes
[x] No
```

chore(deps): lock angular builder version

---

README.md

- [ x] Docs have been added / updated (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x ] No
```

docs: add feedback url

---

docs/advanced/mapped-sub-states.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

Code typos

---

bundlesize.config.json
packages/store/src/internal/dispatcher.ts
packages/store/tests/issues/issue-1687-inject-store-inside-error-handler.spec.ts

```
[x] Bugfix
```
Issue Number: #1687 
```
[ ] Yes
[x] No
```

fix(store): allow to inject the `Store` into the custom error handler

---

docs/concepts/actions.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

Use correct pronoun for subject of sentence

---

docs/concepts/actions.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

Fix subject verb agreement

---

packages/devtools-plugin/package.json
packages/form-plugin/package.json
packages/hmr-plugin/package.json
packages/logger-plugin/package.json
packages/router-plugin/package.json
packages/storage-plugin/package.json
packages/store/package.json
packages/websocket-plugin/package.json

```
[ ] Bugfix
[ ] Feature
[X] Build related changes
```
Issue Number: #1748
Updated peer dependencies to support Angular 12
```
[ ] Yes
[X] No
```

chore: add official support for Angular 12

---

packages/store/tests/action.spec.ts

```
[ ] Bugfix
[ ] Feature
[X] Refactoring (no functional changes, no api changes)
```
The action tests now follow the AAA syntax with a `setup` function as opposed to `beforeEach` and shared variables.
```
[ ] Yes
[x] No
```

chore: clean up action test to follow AAA syntax with setup function

---

tools/publish-dev-builds.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

build: disallow failure dev build job

---

tools/publish-tagged-builds.ts

```
[x] Bugfix
[ ] Feature
```
Related PR: #1778 
A publish failure would result in a failed ci run
```
[ ] Yes
[x] No
```

fix(script): handle tagged build failure correctly

---

docs/recipes/module-federation.md

The first version for a recipe about module federation with ngxs
```
[ ] Bugfix
[ ] Feature
```
Issue Number: https://github.com/ngxs/store/issues/1772
```
[ ] Yes
[x] No
```
This is a first version. Please give me feedback.
The  recipe is based on my experiences and may not be complete.

(docs): module federation recipe

---

docs/concepts/state.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
Simple typo

docs(state): fix typo

---

docs/concepts/state.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs(state): fix link to immer

---

docs/introduction/installation.md

```
[ ] Bugfix
[ ] Feature
```
There is an undefined State in the installation docs, probably left there by accident 
There is now just an empty array there in the forRoot definition 
```
[ ] Yes
[x] No
```

docs(installation): remove unused `ZooState`

---

CHANGELOG.md
bundlesize.config.json
packages/form-plugin/src/form.plugin.ts
packages/form-plugin/tests/form.plugin.spec.ts
packages/form-plugin/tests/issues/issue-1590-update-form-value-primitive.spec.ts

fix(form-plugin): do not destructure primitive types

---

CHANGELOG.md
bundlesize.config.json
integrations/hello-world-ng13-ivy/src/app/issue-1855-extension-fac-property.spec.ts
integrations/hello-world-ng14-ivy/src/app/issue-1855-extension-fac-property.spec.ts
packages/store/internals/src/decorator-injector-adapter.ts

I added the same unit test both for ng13 and ng14, since ng13 uses Jest and ng14 uses Karma.
Issue: #1855
Issue: #1854

fix(store): do not try to decorate factory asynchronously

---

CHANGELOG.md
packages/devtools-plugin/src/devtools.plugin.ts
packages/router-plugin/src/router.state.ts
packages/router-plugin/tests/issues/issue-1640-devtools-time-travel.spec.ts

fix(devtools-plugin): enable time-traveling for navigation actions

---

docs/advanced/operators.md

docs(store): add "Typing Operators" section to `operators.md`

---

.github/workflows/pr-validation.yml
.github/workflows/trunk.yml

```
[ ] Bugfix
[ ] Feature
```
A previous PR #1886 added an experiment to try to approve the bundle size difference.
It did not work as expected, so I am rolling it back.
I have added a feature request to Bundlemon to help with what we need:
https://github.com/LironEr/bundlemon/issues/115
```
[ ] Yes
[x] No
```

ci: remove bundlemon approval step

---

docs/concepts/select.md
packages/store/src/decorators/select/select.ts

Marked it as `chore` since it's not a fix neither a feature.

chore(store): remove `@Select` deprecation notice [for patch release]

---

CHANGELOG.md
docs/plugins/storage.md
packages/storage-plugin/src/engines.ts
packages/storage-plugin/src/internals.ts
packages/storage-plugin/src/internals/final-options.ts
packages/storage-plugin/src/internals/storage-key.ts
packages/storage-plugin/src/public_api.ts
packages/storage-plugin/src/storage.module.ts
packages/storage-plugin/src/storage.plugin.ts
packages/storage-plugin/src/symbols.ts
packages/storage-plugin/tests/issues/issue-598-storage-engine-per-key.spec.ts

feat(storage-plugin): enable providing storage engine individually

---

CHANGELOG.md
package.json
packages/store/src/decorators/selector-options.ts
packages/store/src/decorators/selector/selector.ts
packages/store/tests/selector.spec.ts
yarn.lock

fix(store): get descriptor explicitly when considered as class prop

---

CHANGELOG.md
integrations/hello-world-ng12-ivy/yarn.lock
integrations/hello-world-ng13-ivy/yarn.lock
integrations/hello-world-ng14-ivy/yarn.lock
integrations/hello-world-ng15/yarn.lock
integrations/hello-world-ng16/yarn.lock
package.json

```
[ ] Bugfix
[ ] Feature
```
Prepare for v3.8.1 release
```
[ ] Yes
[x] No
```

chore: release v3.8.1

---

docs/snippets/operators.md

```
[ ] Bugfix
[ ] Feature
```
Issue Number: 2027
```
[ ] Yes
[X] No
```

docs: fix upsertItem operator example

---

docs/advanced/selector-utils.md

doc: fix one Selector code sample that is not compiling
```
[ ] Bugfix
[ ] Feature
```
The provided code sample didn't compile and was misleading, especially because of the lack of [] around AnimalsState in @Selector
The code sample will compile directly when copied to local machine
```
[ ] Yes
[x] No
```

docs: example code not compiling

---

docs/concepts/store.md
docs/introduction/installation.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

docs: update store documentation

---

docs/concepts/actions.md
docs/concepts/state.md
docs/concepts/store.md
docs/introduction/schematics.md
docs/introduction/starter-kit.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

docs: fix paths and provide defaults into schematics

---

packages/store/schematics/src/starter-kit/files/store/auth/auth.state.spec.ts__template__
packages/store/schematics/src/starter-kit/files/store/auth/auth.state.ts__template__
packages/store/schematics/src/starter-kit/files/store/dashboard/index.ts__template__
packages/store/schematics/src/starter-kit/files/store/dashboard/states/user/user.actions.ts__template__
packages/store/schematics/src/starter-kit/files/store/dashboard/states/user/user.state.spec.ts__template__
packages/store/schematics/src/starter-kit/files/store/dashboard/states/user/user.state.ts__template__
packages/store/schematics/src/starter-kit/files/store/store.config.ts__template__

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

feat(store): change the StateModule name into State

---

integration/app/store/todos/todo/todo.state.ts
package.json
packages/hmr-plugin/src/internal/hmr-lifecycle.ts
packages/hmr-plugin/src/internal/hmr-state-context-factory.ts
packages/store/ng-package.json
packages/store/package.json
packages/store/src/internal/internals.ts
packages/store/src/internal/state-context-factory.ts
packages/store/src/symbols.ts
yarn.lock

Revert "fix(store): `ctx.getState` should return `DeepReadOnly<>`"

---

docs/community/sponsors.md
docs/plugins/websocket.md
integrations/hello-world-ng16/src/app/store/store.module.ts
integrations/hello-world-ng17/src/app/store/store.module.ts
packages/store/schematics/src/ng-add/add-declaration.ts
packages/websocket-plugin/README.md
packages/websocket-plugin/index.ts
packages/websocket-plugin/package.json
packages/websocket-plugin/src/private_api.ts
packages/websocket-plugin/src/providers.ts
packages/websocket-plugin/src/public_api.ts
packages/websocket-plugin/src/symbols.ts
packages/websocket-plugin/src/websocket-handler.ts
packages/websocket-plugin/src/websocket.module.ts
packages/websocket-plugin/tests/websocket-handler-cleanup.spec.ts
packages/websocket-plugin/tests/websocket.module.spec.ts

This commit updates all instances of `Websocket` (with a lowercase "s") to `WebSocket` to ensure consistent title casing across the package.

fix(websocket-plugin): `WebSocket` title casing should be consistent

---

docs/concepts/actions/action-handlers.md
docs/concepts/state/life-cycle.md

Also removed some mentions about Angular internal stuff.

docs: update life cycle guide and examples

---

publication/2024-04-05_announcing_ngxs_17/article.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

docs: note the minimum angular version in release notes

---

README.md
packages/store/README.md

```
[ ] Bugfix
[ ] Feature
```
PR #2139 moved location of the `contributors.md` and `sponsors.md` files. This PR adjusts the sources to changes.
```
[ ] Yes
[x] No
```

docs: update contributors/sponsors

---

packages/store/README.md

In this PR I am suggesting using the new logo in the `store` package and replace slack with discord
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

docs(store): update the logo in store package

---

README.md

Use the new logo in the README file
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

docs: update the logo in the main readme file

---

docs/concepts/store/error-handling.md

There have been many questions about the recommended practice with error handling in NGXS.
This PR improves the documentation to assist the user in deciding on an approach that suits their team.
```
[ ] Bugfix
[ ] Feature
```

docs: improve error handling section in docs

---

docs/concepts/store/error-handling.md

```
[ ] Bugfix
[ ] Feature
```

docs: add explanation of deterministic vs non-deterministic errors

---

integration/app/app.component[observable].spec.ts
integration/app/app.component[signal].spec.ts
packages/logger-plugin/jest.config.js
packages/logger-plugin/tests/issues/issue-1551.spec.ts
packages/storage-plugin/tests/storage-for-feature.spec.ts
packages/store/experimental/tests/preboot-wait-stable.spec.ts
packages/store/internals/testing/src/ngxs.setup.ts
packages/store/tests/execution/dispatch-outside-zone-ngxs-execution-strategy.spec.ts
packages/store/tests/execution/noop-ngxs-execution-strategy.spec.ts
packages/store/tests/helpers/counter.state.ts
packages/store/tests/helpers/todo.state.ts
packages/store/tests/issues/issue-2180-dispatching-in-effect.spec.ts
packages/store/tests/lazy-load.spec.ts
packages/store/tests/select-signal.spec.ts
packages/store/tests/selector.spec.ts
packages/store/tests/state.spec.ts
packages/websocket-plugin/tests/websocket-handler-cleanup.spec.ts

```
[ ] Bugfix
[ ] Feature
```
The tests were outputting much console logging, which was making the test result difficult to read.
Skip console logging where necessary.
```
[ ] Yes
[x] No
```

test: clean up tests' console logging

---

.circleci/config.yml
.github/actions/setup/action.yml
package.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

chore: install tutorial packages

---

.circleci/config.yml

```
[ ] Bugfix
[ ] Feature
```
We were having build failures on CircleCI.
This is related to a friefox download issue:
https://github.com/CircleCI-Public/browser-tools-orb/issues/38
Update the CircleCI orb version to fix the issue.
```
[ ] Yes
[x] No
```
-----
<a href="https://stackblitz.com/~/github.com/ngxs/store/tree/markwhitfeld/ci-fix-circleci-browsers-orb"><img src="https://developer.stackblitz.com/img/review_pr_small.svg" alt="Review PR in …

ci: update circleci browsers orb to fix firefox issue

---

docs/community-and-labs/community/projects.md

```
[ ] Bugfix
[ ] Feature
```
Add [angular-authentication](https://github.com/nikosanif/angular-authentication) to Community Projects.
```
[ ] Yes
[x] No
```
N/A

chore(docs): add `angular-authentication` project at community projects

---

.bundlemonrc.json
.github/workflows/pr-validation.yml
.github/workflows/release.yml
.github/workflows/trunk.yml
CHANGELOG.md
integration/tsconfig.json
package.json
yarn.lock

```
[x] Bugfix
[ ] Feature
```
Bundlemon is currently not running due to a "bad project credentials" error.
This PR moves to use the github action and v2 of the bundlemon api in the hope that this will resolve the issue.
```
[ ] Yes
[x] No
```

fix(ci): move to bundlemon v3

---

docs/concepts/store/README.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs: fix README.md formulation and imports
