README.md, package-lock.json, package.json, src/index.ts, src/module.ts, src/plugins/redux-devtools.ts, src/symbols.ts
Adds support for the redux-devtools.
This fixes also the type for the `plugins` array in the options. It was not possible to provide a class name in the configuration.
Open issue: I'm not able to inject `Ngxs` into the Plugin (it's always `undefined`). So I'm not able to set the initial state.
=> feat: support redux-devtools

README.md, src/index.ts, src/plugins/localstorage.ts
Most of the fixes are small spelling mistakes. One thing you might want to review is I changed LocalStorage to be pascal case, example:  
LocalstoragePluginOptions  -> LocalStoragePluginOptions
so it's not mixed case.  /Mike
=> fix: Spelling and Capitalization

docs/concepts/README.md, docs/concepts/event.md, docs/concepts/mutation.md, docs/concepts/select.md, src/factory.ts, src/ngxs.ts
If I understand ngxs correct, you're always dispatching an event and then you'll use the action/mutation decorators to handle the events. Which is different from ngrx, where you dispatch an action.
It seems like the concept is mixed in the source code. I renamed some variables based on the above statement. If I'm wrong, please just ignore this PR. /Mike
=> chore: event vs action

docs/plugins/README.md, docs/plugins/devtools.md, docs/plugins/localstorage.md, docs/plugins/logger.md, integration/app/app.module.ts, src/index.ts, src/module.ts, src/plugin-manager.ts, src/plugins/localstorage.ts, src/plugins/logger.ts, src/plugins/redux-devtools.ts, src/symbols.ts
@amcdnl putting the work here so you can see it. closes #16 
The API will use a plugins DI token for the plugin classes and each plugin will use it's own *_OPTIONS token to configure the plugin. The plugin can then be provided either manually (not recommended) or use the plugin module with a *.forRoot() method.
```TS
@NgModule({
imports: [
NgxsModule.forRoot([TodoStore]),
LocalStoragePluginModule.forRoot({ ... })
]
})
```
the example forRoot implementation for the localstorage plugin looks like:
```TS
export function serialize(val: any) {
return JSON.stringify(val);
}
export function deserialize(val: any) {
return JSON.parse(val);
}
@NgModule()
export class LocalStoragePluginModule {
static forRoot(options: LocalStoragePluginOptions = {}): ModuleWithProviders {
return {
ngModule: …
```
=> feature/plugins: update plugins with proposed api

integration/app/app.component.spec.ts, integration/app/app.component.ts, integration/app/app.module.ts, package.json, src/internals.ts, src/select.ts, src/spec/select.spec.ts, src/state-factory.ts, src/state.ts
Fixes issue where selecting substate with a class would return undefined. A state "path" is now added to metadata when children are present
The StateFactory now adds the path property to each class on init.
NOTE: may have uncovered another issue with sub states if you include the substate in the forRoot method BEFORE the root
=> fix(core): class selector

src/spec/action.spec.ts, src/spec/state.spec.ts, src/state.ts, src/symbols.ts
this PR makes "name" a required property for the state decorator to help avoid issues with minification. fixes #72
=> fix(core): inferring state name breaks with uglify

docs/plugins/README.md, docs/plugins/devtools.md, docs/plugins/localstorage.md, docs/plugins/logger.md, integration/app/app.module.ts, src/index.ts, src/plugins/devtools/devtools.module.ts, src/plugins/devtools/devtools.plugin.ts, src/plugins/devtools/index.ts, src/plugins/devtools/symbols.ts, src/plugins/localstorage/index.ts, src/plugins/localstorage/localstorage.module.ts, src/plugins/localstorage/localstorage.plugin.spec.ts, src/plugins/localstorage/localstorage.plugin.ts, src/plugins/localstorage/symbols.ts, src/plugins/logger/index.ts, src/plugins/logger/logger.module.ts, src/plugins/logger/logger.plugin.ts, src/plugins/logger/symbols.ts
Rename plugin modules and classes to include Ngxs prefix
closes #87 
BREAKING CHANGE:
`LoggerPlugin` is now `NgxsLoggerPlugin`
`LoggerPluginModule` is now `NgxsLoggerPluginModule`
`LocalStoragePlugin` is now `NgxsLocalStoragePlugin`
`LocalStoragePluginModule` is now `NgxsLocalStoragePluginModule`
`ReduxDevtoolsPlugin` is now `NgxsReduxDevtoolsPlugin`
`ReduxDevtoolsPluginModule` is now `NgxsReduxDevtoolsPluginModule`
=> refactor(plugins): ngxs prefix

docs/concepts/state.md
Fixes a `[ts] Cannot find name 'state'.` error.  This tripped me up for a couple minutes.
=> Missing getState() call before patchValues

docs/concepts/state.md, docs/plugins/README.md, package.json, src/actions/init.ts, src/module.ts, src/spec/module.spec.ts, src/symbols.ts
I was having troubles when having `NgxsModule.forFeature` in the main app.
It seems that the provider store token was being injected multiple times which caused feature's to be loaded twice.
By separating out the feature states into it's own token it seems to be working better.
I Also added some units tests to test out the different setups we can encounter.
The pull request is also tested against `--aot` and everything seems to be working.
@amcdnl  Could you have a look and see if this improves things?
=> feat: improved module init

docs/concepts/state.md
Addded missing parenthesis to the `map` function
=> fix(docs): add missing parenthesis

src/store.ts
Hey!
I'm currently evaluating using ngxs for a large Angular app and so far it looks great. I'm particularly interested in the type-safety of selecting data from the store and I think this improves it for the `store.select()` approach.
A simple example:
```ts
interface User {
name: string;
}
interface State {
users: User[];
}
// this will type check but is wrong as actually userNames$ will be Observable<number>
const userNames$: Observable<string> = store.select((state: State) => state.users.length);
```
With this additional function signature I get this error:
```
[ts]
Type 'Observable<number>' is not assignable to type 'Observable<string>'.
Type 'number' is not assignable to type 'string'.
```
=> feat: add overloading to select method in Store

packages/store/src/actions-stream.ts
This will keep any new subscribers to the action stream from getting old actions
=> refactor(store): action stream should use Subject

packages/store/src/action.ts, packages/store/src/internals.ts, packages/store/tests/action.spec.ts, packages/store/tests/dispatch.spec.ts, packages/store/tests/state.spec.ts
The goal of this PR is to mitigate any minification or name collision issues.
My First thought was to use Symbol but since that isn't supported by any IE browsers id rather not force folks to depend on a polyfill so I am thinking use a small Token class and use that as the token if none is provided. The hope here is to create completely unique actions without depending on the user to add a static property themselves. 
Questions:
How would this impact plugins?
Are there performance implications?
Fixes #200
@amcdnl @leon
=> fix(store): always set action type

docs/introduction/installation.md
Removes a doubled word (`install`).
Adds a '.'
Go to upperCase for 2 letters.
Just that ^^
=> (docs/intro): typo fix & just a little more

docs/advanced/cancelation.md, packages/store/src/state-factory.ts, packages/store/src/symbols.ts, packages/store/tests/dispatch.spec.ts
As discussed here is the PR for the name change.
@amcdnl @deebloo After our back and forth over `cancelUncompleted` and `cancelsUncompleted` I settled on `cancelUncompleted` to match the same instructional tone as how rxjs pipes are named.
It will follow on from this that the Action Pipes that we are soon to create should generally have the same name as the option.
=> feat(store): rename takeLast @Action option to cancelUncompleted (#191)

docs/concepts/store.md
I found it a bit weird to read about actions, but suddenly they are named events, I think it would be better to change this, to avoid confusion.
=> chore(docs): concepts/store fix typos and change naming from Events to Actions

docs/SUMMARY.md, docs/concepts/actions.md
Since in the whole docs, action it actually always mentioned in its plural form, I think it would be better to change the title and file name as well.
=> chore(docs): concepts/actions, rename file and fix typos

docs/README.md
gitbooks link also responds with 404. I assume it needs to be replaced with https://ngxs.gitbook.io/ngxs/concepts
=> Fix concepts link

docs/plugins/form.md
The `ngxsForm` used by form-plugin is a directive therefore must be imported in every module. This PR adds this information to the documentation.
=> chore(docs): add info about using form-plugin in submodule

packages/store/tests/state.spec.ts
This updates lifecycle tests to use the available state management mechanism. This ensures that state is also set in the correct order.
=> refactor: update tests to use internal state management

docs/recipes/authentication.md
- Changed 'goto' to 'go to'
- Changed the description of the `canActivate`  guard
=> chore(docs): fix typos

docs/advanced/cancellation.md, docs/advanced/life-cycle.md, docs/advanced/shared-state.md, docs/advanced/sub-states.md, docs/concepts/actions.md, docs/concepts/intro.md, docs/concepts/select.md, docs/concepts/state.md, docs/concepts/store.md, docs/introduction/installation.md, docs/plugins/websocket.md, docs/recipes/cache.md, docs/recipes/style-guide.md
To better cater for new developers which haven't become familiar with destructuring of types.
I have rewritten the docs to use:
```TS
@Action(FeedAnimals)
feedAnimals(ctx: StateContext<ZooStateModel>, action: FeedAnimals) {...}
```
https://github.com/ngxs/store/blob/feature/docs-ctx-update/docs/concepts/actions.md#how-should-you-name-your-actions
and the mental model you should use when designing your app.
Based on the great talk by Mike Ryan https://www.youtube.com/watch?v=JmnsEvoy-gY
What do you guys think of having a section about the mental model for actions, is it any good?
=> docs: removed destructuring of StateContext and Actions

packages/router-plugin/src/router.module.ts, packages/router-plugin/src/router.state.ts, packages/storage-plugin/src/symbols.ts, packages/store/src/actions-stream.ts
- Fixes enums getting compiled out at prod build time
- Fixes race case when loading router module in production
- Properly imports the router module using `@dynamic`
- Minor code cleanup
=> fix(store): fix enum compile out

README.md
The link is pointing to the wrong path.
=> docs: readme contributor link

docs/concepts/actions.md
By example, there was no verb added to the ArchiveProject, 
so I think the entity to act upon is Project and the verb is Archive.
=> Renaming ArchiveProject to Project

.github/ISSUE_TEMPLATE.md
Added text to issue template requesting a stackblitz link  as a repo if possible.
Much easier to reproduce the issue and verify the fix afterwards if provided.
Also provided a sample link that, if followed, would give them a forked version of the simple ngxs sample.
=> chore: add request for stackblitz repro link to issue template

packages/store/src/dispatcher.ts
Runs actions outside of zones for performance reasons.
=> fix(perf): run actions outside zones for perf

packages/store/src/state-factory.ts
Removes the error from being throw if the state has already been added. This can happen when you want to lazy load the same store from different paths via lazy loading.
=> fix(state): remove error for multiple states

packages/store/src/dispatcher.ts, packages/store/src/zone.ts, packages/store/tests/dispatch.spec.ts
This moves the `subscribe` function of the dispatch back into a angular zone.
=> fix(store): move the subscribe into a zone

packages/store/src/entity-base.ts, packages/store/tests/entity-base.spec.ts
Mutations were changing the entire store instead of only the correct state
=> fix: mutations were overwriting the entire store

packages/store/src/internals.ts, packages/store/src/module.ts, packages/store/src/state-context-factory.ts, packages/store/src/state-operations.ts, packages/store/src/store.ts
This consolidation is required for the freeze functionality of the development mode.
This is so that all internal `dispatch` and `setState` operations go through a single point so that they can be intercepted and frozen. This could also be a useful point to gather debug information.
PS. Kept the `StateOperations` interface internal and reverted the plugin interface (as opposed to the last PR).
=> Consolidate internal state operations

packages/router-plugin/index.ts
I need these imports:
```
import { RouterState } from '@ngxs/router-plugin';
import { RouterStateModel } from '@ngxs/router-plugin/src/router.state';
```
to use this:
```
this.store.select(RouterState)
.subscribe((route: RouterStateModel) => console.log(route.state));
```
And I think it should be better:
```
import { RouterState, RouterStateModel } from '@ngxs/router-plugin';
```
=> feat: expose RouterStateModel in @ngxs/router-plugin

docs/concepts/select.md
This PR fixes a small typo in `select.md`.
=> fix(select.md): fix small typo

docs/plugins/router.md
The Navigate action in router-plugin takes an array of paths, just like the navigate method of angular-router.
=> doc: update Router Plugin doc.

docs/advanced/cancellation.md
This PR cleans up a sentence.
The part "such as using specifying based on tokens" sounds a bit weird and may be obsolete.
=> fix(cancellation.md): clean up sentence

docs/concepts/state.md
fixes a bug in example code where an interface with wrong name is used
=> docs: fix example on state.md

packages/store/src/entity-base.ts, packages/store/src/state-base.ts
Use NgxsOnInit to avoid inherit from StateBase
I believe with this approach, there is some advantages:
- Simple classes
- Maybe StateBase isn't neccessary anymore, so it's possible to use it without Store modifications
=> feat: entity base with NgxsOnInit

docs/recipes/authentication.md
token and username could not be empty.
There's also another solution for that:
```
export class AuthStateModel {
token: string;
username: string;
}
const AuthStateDefaults: AuthStateModel = {
token: null,
username: null,
};
@State<AuthStateModel>({
name: 'auth',
defaults: AuthStateDefaults,
})
```
And in the action:
`setState(AuthStateDefaults)`
=> fix(docs): set empty state not working

packages/store/src/public_api.ts
```
[x] Bugfix
[ ] Feature
```
Action stream ofActionCanceled is not exposed in the store public api.
Issue Number: #526 
Add ofActionCanceled into public api file and reorder the exports just like in the of-action file.
```
[ ] Yes
[x] No
```
=> fix(store): expose ofActionCanceled function

docs/recipes/unit-testing.md
```
[ ] Bugfix
[ ] Feature
```
Unit test ending before the expect is checked.
Issue Number: Slightly related to #379 
Unit test function containing subscription must be wrapped with async().
```
[ ] Yes
[x] No
```
=> fix(docs): unit test function must be wrapped with async()

integration/app/app.component.spec.ts
```
[x] Bugfix
[ ] Feature
```
Errors appear in the integration test since storage plugin been added, for example:
```Bash
ERROR: 'ERROR', TypeError: Cannot read property 'concat' of undefined
TypeError: Cannot read property 'concat' of undefined
at TodoState../integration/app/todo.state.ts.TodoState.addTodo (http://localhost:9876/_karma_webpack_/webpack:/integration/app/todo.state.ts:34:28)
```
But the tests itself isn't failing.
Todos state is initialized with a valid initial state, instead of an empty object.
```
[ ] Yes
[x] No
```
=> fix(integration): errors in integration test

docs/concepts/select.md
This reverts commit ca278b322716e326806b55ad00d66eff4992d744 from PR ngxs/store#562
Did not see the misplaced brackets in the review
=> revert: docs(store): typos in concepts/select

packages/store/src/internal/internals.ts, packages/store/src/internal/state-factory.ts, packages/store/src/module.ts, packages/store/src/symbols.ts, packages/store/src/utils/selector-utils.ts
Setting the config option of strictContentSecurityPolicy to true will avoid CSP violations
```
[X] Bugfix
[X] Feature
```
Issue Number: #516 #439 
Add a config setting to allow for a strict Content Security Policy.
There will be a small performance hit to selectors because this circumvents an optimisation.
This should be provided in the ngxs options to the root module as follows:
```TS
NgxsModule.forRoot([
ZooState
], {
compatibility: {
strictContentSecurityPolicy: …
```
=> feat: add strictContentSecurityPolicy compatibility rule

packages/devtools-plugin/package.json, packages/form-plugin/package.json, packages/logger-plugin/package.json, packages/router-plugin/package.json, packages/storage-plugin/package.json, packages/store/package.json, packages/websocket-plugin/package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Update Peer Dependencies
```
Currently when installed with Angular 7 npm produces warnings, for example:
```bash
npm WARN @ngxs/devtools-plugin@3.2.0 requires a peer of @angular/core@>=5.0.0 <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngxs/logger-plugin@3.2.0 requires a peer of @angular/core@>=5.0.0 <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN …
```
=> Update peer Dependencies in order for Angular 7 to be in range

.yarnrc, package.json, yarn.lock
```
[ ] Bugfix
[ ] Feature
```
https://github.com/yarnpkg/yarn/issues/5891
```
[ ] Yes
[x] No
```
unused package was removed ("rxjs-compat": "^6.0.0")
https://update.angular.io/
Remove deprecated RxJS 6 features using rxjs-tslint auto update rules
For most applications this will mean running the following two commands:
yarn global add rxjs-tslint
rxjs-5-to-6-migrate -p src/tsconfig.app.json
=> fix(store): deprecating registry.yarnpkg.com

packages/storage-plugin/src/storage.plugin.ts, packages/storage-plugin/tests/storage.plugin.spec.ts
```
[x] Bugfix
[ ] Feature
```
When there is nothing in the store and you are using NgxsPluginModule.forFeature, additional slices that should be initialized in @@UpdateState by the feature are overwritten by the slices in the global state that were saved to storage on the first pass of @@InitState
Any slices from a feature that are undefined in the current state are added with their initial value.
```
[ ] Yes
[x] No
```
=> fix(storage-plugin): lazy loaded slices not initialized

packages/form-plugin/src/form.plugin.ts, packages/form-plugin/tests/form.plugin.spec.ts
add check in form.plugin.ts to check if payload value is an array and process it accordingly 
no breaking change
```
[x] Bugfix
[ ] Feature
```
Issue Number: #655 
It will now accept forms that are form array
Example:
```
this.form = this.fb.array([
this.fb.control(null),
this.fb.control(null)
]);
```
```
[ ] Yes
[x] No
```
=> fix(form-plugin): fix form-plugin to accept form arrays

packages/store/src/decorators/state.ts, packages/store/tests/store.spec.ts
```
[x] Bugfix
[ ] Feature
```
underscores in state name return an error saying the state name isn't valid because it is not a 'valid object property name'
underscores are allowed in state name
```
[ ] Yes
[x] No
```
=> fix(store): included underscore in stateNameRegex

docs/concepts/actions.md, docs/concepts/state.md, docs/concepts/store.md
A few quick fixes for the actions, state and store docs.
```
[ ] Bugfix
[ ] Feature
```
There were a few grammatical or spelling mistakes in the docs that can be confusing to a reader. I feel the changes will help add to the value of the docs a little.
NA
```
[ ] Yes
[x] No
```
=> docs: Minor Spelling and Grammar Changes

package.json
Reverts ngxs/store#714
This new single quoted form does not work in windows.
=> Revert "style(prettier): fix format script"

packages/store/src/internal/state-operations.ts, packages/store/src/utils/angular.ts, packages/store/tests/utils/angular.spec.ts
```
[X] Bugfix
[ ] Feature
```
We wanted to remove the console hints if Angular was in testing mode.
In order to detect if Angular is in testing mode we injected TestBed but this has increased the production bundle size by 78kb!
Issue Number: #722 #706 #701 
Removed ref to TestBed and used a different machanism to determine test mode.
```
[ ] Yes
[X] No
```
=> fix(store): remove TestBed ref to reduce bundle size

docs/advanced/action-handlers.md
```
[ ] Bugfix
[ ] Feature
```
Missing information about the interface returned by `ofActionCompleted` in the docs.
Issue Number: #718
Added some basic information about the returned object.
```
[ ] Yes
[X] No
```
=> docs(store): add basic docs for structure returned by ofActionCompleted

docs/plugins/storage.md, packages/storage-plugin/src/symbols.ts, packages/storage-plugin/tests/storage.plugin.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #771
The StorageEngine interface doesn't require implementing the `key` method.
```
[ ] Yes
[x] No
```
=> fix(storage-plugin): Remove the 'key' feature from the 'StorageEngine' interface

docs/plugins/storage.md
Remove the 'key' method implementation.
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #771
Update an example following a [PR](https://github.com/ngxs/store/pull/790) that changed the StorageEngine interface.
```
[ ] Yes
[x] No
```
=> docs(storage-plugin): update `storage-plugin` example

packages/store/src/decorators/state.ts, packages/store/src/internal/internals.ts, packages/store/src/internal/state-factory.ts, packages/store/src/internal/state-operations.ts, packages/store/src/internal/state-stream.ts, packages/store/src/module.ts, packages/store/src/store.ts, packages/store/src/symbols.ts, packages/store/src/utils/store-validators.ts, packages/store/tests/action-handler.spec.ts, packages/store/tests/default-states.spec.ts, packages/store/tests/store-validator.spec.ts, tsconfig.json
```
[x] Bugfix
[x] Feature
```
Issue Number: 
https://github.com/ngxs/store/issues/179
https://github.com/ngxs/store/issues/741
https://github.com/ngxs/store/issues/719
throw an error, since the previous state will be overwritten
```
[ ] Yes
[x] No
```
=> feat(store): reusable states

docs/SUMMARY.md, docs/advanced/operators.md
```
[ ] Bugfix
[ ] Feature
```
#786 
```
[ ] Yes
[x] No
```
=> docs(store): add docs about state operators

packages/logger-plugin/src/logger.plugin.ts, packages/logger-plugin/tests/helpers/index.ts, packages/logger-plugin/tests/helpers/logger-spy.ts, packages/logger-plugin/tests/helpers/symbols.ts, packages/logger-plugin/tests/helpers/utils.ts, packages/logger-plugin/tests/logger.plugin.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #817 
I added the `error` log in case the error raised is suppressed with a custom error handler after the logger ran.
```
[ ] Yes
[x] No
```
=> fix(logger): log group not closed on error

packages/websocket-plugin/src/websocket-handler.ts, packages/websocket-plugin/tests/websocket.module.spec.ts
```
[x] Bugfix
[ ] Feature
```
currently client triggered websocket disconnect will dispatch WebSocketDisconnected where as server/network err triggered disconnect dispatches WebsocketMessageError (this is how rxjs websocket subject works). NGXS websocket plugin's API consumer should not have to deal with these low level scenarios, and any type of disconnecting should dispatch WebSocketDisconnected
With this change, server disconnect will also trigger …
=> fix(websocket-plugin): Server/network error triggered close should dispatch WebSocketDisconnected

CHANGELOG.md, packages/hmr-plugin/src/internal/hmr-lifecycle.ts, packages/store/operators/src/internals.ts, packages/store/operators/src/utils.ts, packages/store/src/internal/internals.ts, packages/store/src/store.ts
```
[X] Bugfix
[ ] Feature
```
Client project build fails when using Angular 5/6 with TS 2.7.
The build does not fail because I removed the incompatible typings.
```
[ ] Yes
[X] No
```
=> fix(store): remove typings that are incompatible with TS 2.7

docs/plugins/hmr.md, packages/hmr-plugin/src/hmr-bootstrap.ts, packages/hmr-plugin/src/hmr-manager.ts, packages/hmr-plugin/src/internal/hmr-lifecycle.ts, packages/hmr-plugin/src/internal/hmr-options-builder.ts, packages/hmr-plugin/src/public_api.ts, packages/hmr-plugin/src/symbols.ts, packages/hmr-plugin/src/tests/hmr-manager.spec.ts, packages/hmr-plugin/src/tests/hmr-mock.ts, packages/store/tests/zone.spec.ts
```
[X] Bugfix
[ ] Feature
[X] Refactoring (no functional changes, no api changes)
```
Many of the hmr plugin interfaces had type parameters that were not necessary and were left over from earlier development on the plugin. These were making the interfaces confusing.
Also, if the `NgxsHmrLifeCycle` was not implemented by the `AppModule` then hmr would not persist or load anything.
Trimmed down interfaces.
Added default behaviour if the `NgxsHmrLifeCycle` was not implemented by the `AppModule`.
The plugin …
=> fix(hmr): add default behaviour and trim down hmr interfaces

packages/form-plugin/src/directive.ts, packages/form-plugin/tests/form.plugin.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #861
The FormGroup value of the 'dirty' flag is now equal to the store value on first rendering. Switching the order of the subscriptions around in ngOnInit of the ngxsForm directive ensures that the current store value is reflected in the FormGroup before the actions that update the store are dispatched.
```
[ ] Yes
[x] No
```
=> fix(form-plugin): respect store value of 'dirty' flag (#861)

packages/router-plugin/src/router.state.ts, packages/router-plugin/tests/router.plugin.spec.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #893 
Now is possible to select the router state correctly typed when using the `state` selector like this:
```
store
.select(state => RouterState.state<RouterStateParams>(state.router))
.subscribe(routerState => {
expect(routerState!.url).toEqual('/a-path?foo=bar');
expect(routerState!.queryParams.foo).toEqual('bar');
});
```
```
[ ] Yes
[x] No
```
=> fix(router-plugin): add state selector with generic

packages/store/src/store.ts, packages/store/tests/default-states.spec.ts
```
[X] Bugfix
[ ] Feature
```
Issue Number: #902
There was a regression caused by PR #791 in this line: 
https://github.com/ngxs/store/pull/791/files#diff-084c7b85b6562e3126b58451d5f8943aR20
This only affects Emitter plugin users. This is because of the way that Emitter inherits from Store to create an EmitStore. I found the point at which the state was being overwritten. See this stackblitz:
https://stackblitz.com/edit/ngxs-no-initial-state-debug
Ngxs does not expect …
=> fix(store): initial state should not be overwritten by defaults

docs/plugins/hmr.md, integrations/hello-world-ng5/src/main.ts, packages/hmr-plugin/src/hmr-bootstrap.ts, packages/hmr-plugin/src/hmr-manager.ts, packages/hmr-plugin/src/tests/hmr-helpers.ts, packages/hmr-plugin/src/tests/hmr-manager.spec.ts, packages/hmr-plugin/src/tests/hmr-mock.ts
```
[x] Bugfix
[ ] Feature
```
https://github.com/ngxs/store/issues/887
Webpack in new versions independently destroys modules for us
```
[ ] Yes
[x] No
```
=> fix(hmr-plugin): incorrect destruction of modules in hmr

packages/logger-plugin/src/logger.plugin.ts, packages/logger-plugin/tests/helpers/utils.ts, packages/logger-plugin/tests/logger.plugin.spec.ts
```
[x] Bugfix
[ ] Feature
```
```ts
export class AddTodo {
public static type = 'AddTodo';
constructor(public todo: Todo) {}
}
```
The logger doesn't print action's payload if there's no property called `payload`.
Issue Number: #871 
If the action has at least one property with a value, it will be printed to the console.
```
[ ] Yes
[x] No
```
=> fix(logger): print action properties

packages/store/src/actions/actions.ts, packages/store/src/module.ts, packages/store/tests/state.spec.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #838 
State names array is being added to the `UpdateState` action, so they will be visible using the `logger` and `devtools` plugins.
The `states` parameter is optional in order to prevent a breaking change, in case some developer used this action directly. We might consider changing that to be required for version 4. #827 
```
[ ] Yes
[x] No
```
=> fix(store): add state names to update state

integration/app/list/list.component.html, integration/app/list/list.component.ts, integration/app/list/list.module.ts, integration/app/list/list.resolver.ts, integration/app/list/list.routes.ts, integration/app/store/store.module.ts, integration/tests-ssr/todo.mocha.ts, packages/router-plugin/src/router.module.ts, packages/router-plugin/src/router.state.ts, packages/router-plugin/src/serializer.ts, packages/router-plugin/tests/router.plugin.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #481 
Right now `serialize` is triggered in the `beforePreactivation` hook. Before preactivation is handled before running guards and resolvers. I've moved it to the `ResolveEnd` hook
```
[ ] Yes
[x] No
```
=> fix(router-plugin): serialize after `ResolveEnd`

CHANGELOG.md, packages/store/src/actions/actions.ts, packages/store/src/module.ts, packages/store/tests/state.spec.ts
Reverts ngxs/store#845
This should not have been merged because it is a feature and we are still doing bug fixes on master.
The api that this feature adds is also still in discussion (https://github.com/ngxs/store/pull/845#issuecomment-471702349)
=> revert: "feat(store): add state names to update state"

docs/advanced/operators.md
add type safety to state operator example
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> docs: add type safety to state operator example

packages/logger-plugin/src/logger.plugin.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #923
```
[ ] Yes
[x] No
```
=> fix(logger-plugin): replace `Object.entries` as it breaks IE11

packages/store/src/decorators/selector.ts, packages/store/src/internal/internals.ts, packages/store/src/internal/state-factory.ts, packages/store/src/utils/selector-utils.ts, packages/store/tests/selector.spec.ts
```
[ ] Bugfix
[X] Feature
```
There is currently an issue where the state of the container class of a selector is always injected as the first parameter. This is a problem because it makes the memoisation of every selector defined in a state class dependent on the entire state class, and therefore they are recalculated on any change within the state.
(I will populate the list of realted issues later) 
This PR introduces some internal representations …
=> feat: add selector options to metadata

packages/store/src/actions/actions.ts, packages/store/src/modules/ngxs-feature.module.ts, packages/store/tests/state.spec.ts
```
[ ] Bugfix
[x] Feature
```
The comeback of PR #845, with one change - `payload` parameter has been changed to `addedStats`.
Issue Number: #838 
State defaults array is being added to the `UpdateState` action, so they will be visible using the `logger` and `devtools` plugins.
The `payload` parameter is optional in order to prevent a breaking change, in case some developer used this action directly. We might consider changing that to be required for version 4. #827 …
=> feat(store): add state defaults to UpdateState

packages/store/src/internal/internals.ts, packages/store/src/internal/state-factory.ts, packages/store/src/symbols.ts, packages/store/src/utils/selector-utils.ts, packages/store/tests/selector.spec.ts
```
[x] Bugfix
[ ] Feature
```
https://github.com/ngxs/store/issues/843
```ts
@NgModule({
imports: [
NgxsModule.forRoot([TasksState], {
developmentMode: true,
selectorOptions: { suppressErrors: false }
})
]
})
```
```
[ ] Yes
[x] No
```
=> fix(store): disable suppressing errors in selector

packages/store/src/decorators/selector-options.ts, packages/store/src/decorators/selector.ts, packages/store/src/decorators/selectorOptions.ts, packages/store/src/internal/internals.ts, packages/store/src/internal/state-factory.ts, packages/store/src/modules/ngxs-root.module.ts, packages/store/src/symbols.ts, packages/store/src/utils/selector-utils.ts, packages/store/tests/selector.spec.ts
```
[ ] Bugfix
[x] Feature
```
There is currently an issue where the state of the container class of a selector is always injected as the first parameter. This is a problem because it makes the memoisation of every selector defined in a state class dependent on the entire state class, and therefore they are recalculated on any change within the state.
(I will populate the list of realted issues later) 
Issue Numbers...
See: …
=> feat(store): add SelectorOptions decorator

docs/advanced/options.md, packages/store/src/module.ts, packages/store/src/public_api.ts, packages/store/src/symbols.ts
```
[ ] Bugfix
[x] Feature
```
Now it is not clear how to specify the data type.
The ability to specify in your code what type of data the settings have
```
[ ] Yes
[x] No
```
=> feat(store): expose NgxsModuleOptions as a named type

docs/advanced/options.md, docs/concepts/select.md, docs/introduction/installation.md, packages/store/src/decorators/selector-options.ts, packages/store/src/decorators/selector.ts, packages/store/src/public_api.ts, packages/store/tests/selector.spec.ts, packages/store/types/tests/selector-options.lint.ts
```
[ ] Bugfix
[x] Feature
```
Selector options is only exposed as a global setting. 
The new `@SelectorOptions` decorator was left internal by PR #1029.
Issue Numbers...
See: #386 (comment)
Related: #541 #446
Related PRs: #858, #954, #1015, #1029
Expose the new `@SelectorOptions` decorator and add the relative docs for it.
```
[ ] Yes
[X] No
```
=> feat: expose SelectorOptions decorator

docs/plugins/form.md, packages/form-plugin/src/directive.ts, packages/form-plugin/tests/form.plugin.spec.ts
make the form-plugin dispatch actions immediately when the form's updateOn is 'blur' or 'submit' or when the ngxsFormDebounce is less than zero
```
[X] Bugfix
[ ] Feature
```
https://github.com/ngxs/store/issues/365
Issue Number: 365
When a ngxsFormDebounce is less than zero or when a FormGroup's updateOn property is configured with 'blur' or 'submit', the debounceTime operator will be remove from the valueChanges and statusChanges pipes.
It seems that even with a …
=> fix(form-plugin): introduce conditional debounce

packages/store/operators/src/insert-item.ts, packages/store/operators/src/remove-item.ts, packages/store/operators/src/update-item.ts
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #1055 
```
[ ] Yes
[x] No
```
=> perf(store): replace `spread` with `slice` in the operator functions

packages/store/internals/src/index.ts, packages/store/internals/src/symbols.ts, packages/store/internals/testing/src/symbol.ts, packages/store/src/decorators/state.ts, packages/store/src/internal/internals.ts, packages/store/src/internal/state-factory.ts, packages/store/src/module.ts, packages/store/src/modules/ngxs-feature.module.ts, packages/store/src/modules/ngxs-root.module.ts, packages/store/src/plugin_api.ts, packages/store/src/utils/store-validators.ts, packages/store/tests/action-handler.spec.ts, packages/store/tests/selector.spec.ts
Reverts ngxs/store#1042
This PR should never have been merged.
It exposes too much of the internal NGXS implementation details.
Hopefully the new extensibility model allows for the hooks that this was intended to expose.
=> fix(store): trim down StateClass interface and move it to internals subpackage

packages/websocket-plugin/src/public_api.ts, packages/websocket-plugin/src/symbols.ts, packages/websocket-plugin/src/websocket-handler.ts, packages/websocket-plugin/src/websocket-subject.ts, packages/websocket-plugin/tests/websocket.module.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #977 
```
[ ] Yes
[x] No
```
=> fix(socket-plugin): don't stop WebSocketSubject stream after dispatching WebSocketDisconnected

docs/advanced/sub-states.md
```
[ ] Bugfix
[ ] Feature
```
https://github.com/ngxs/store/issues/566
https://github.com/ngxs/store/issues/1073
=> docs(store): add warning about sub-state erasure

docs/advanced/lazy.md
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #868
=> docs(store): update docs regarging feature states

docs/concepts/state.md
Change "imperitive" to "imperative"
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> docs: fix a typo

integration/app/app.server.module.ts, packages/storage-plugin/src/storage.module.ts, packages/storage-plugin/src/storage.plugin.ts
```
[X] Bugfix
[ ] Feature
```
Issue Number: #1118 
Storage during SSR is emulated with an empty in memory storage engine, which can still be modified by the user by providing a different storage engine.
```
[ ] Yes
[X] No
```
=> fix(storage-plugin): fix undefined localStorage error during SSR (#1118)

packages/store/operators/src/append.ts, packages/store/operators/src/iif.ts, packages/store/operators/src/insert-item.ts, packages/store/operators/src/internals.ts, packages/store/operators/src/remove-item.ts, packages/store/operators/src/update-item.ts, packages/store/operators/src/utils.ts, packages/store/types/index.d.ts, packages/store/types/tests/state-operators.append.lint.ts, packages/store/types/tests/state-operators.iif.lint.ts, packages/store/types/tests/state-operators.insert-item.lint.ts, packages/store/types/tests/state-operators.update-item.lint.ts
```
[x] Bugfix
[ ] Feature
```
After upgrading to the more recent versions of Typescript (3.4 for example) the types narrow too far and do not recognize true or false as compatible with boolean.
Introduced a `RepairType` conditional type to repair the type specificity.
```
[ ] Yes
[x] No
```
=> fix: typescript 3.4 has issues seeing true / false as boolean

packages/router-plugin/src/router.state.ts
```
[x] Bugfix
[ ] Feature
```
The manual path check gives an error when run in SSR.
It doesn't have a big impact other than an error being logged.
It uses the correct platform location instead of the browser specific `window.location` object.
```
[ ] Yes
[X] No
```
=> fix(router-plugin): manual path check should not fail for SSR

packages/router-plugin/src/router.state.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1153
`location.pathname` is concatenated with `location.search` as it has to be.
```
[ ] Yes
[x] No
```
=> fix(router-plugin): serialize entered URL and compare with the recognized one

packages/router-plugin/src/router.state.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1174
`Location.normalize()` strips base href from the provided URL
```
[ ] Yes
[x] No
```
=> fix(router-plugin): normalize URL by stripping base href

package.json, packages/store/types/tslint.json, yarn.lock
Now it is possible to use for type testing the version of TypeScript that is used to build the application.
=> build: fix dtslint problem

tools/utils.ts
```
[ ] Bugfix
[ ] Feature
```
During the last publish (v3.5) there was a glitch that caused one package to fail to be published.
We should retry at least once
Retry pcakage publishing at least once.
```
[ ] Yes
[x] No
```
=> chore: publish should retry at least once

packages/hmr-plugin/src/hmr-manager.ts, packages/hmr-plugin/src/tests/hmr-helpers.ts, packages/hmr-plugin/src/tests/hmr-manager.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: https://github.com/ngxs/store/issues/1190
Trigger ngOnDestroy for all components before destroy AppModule for avoid memory leak
```
[ ] Yes
[x] No
```
=> fix(hmr-plugin): trigger ngOnDestroy for all components in app tree

docs/plugins/storage.md
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #423 
```
[ ] Yes
[ ] No
```
PR description: currently the `key` option is a bit confusing for our users. We have to provide them information to understand that `key` is a name of state/states.
=> docs(storage-plugin): enhance docs about `key` option

packages/router-plugin/src/router.state.ts, packages/router-plugin/tests/helpers.ts, packages/router-plugin/tests/router-cancel.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #542 
The state is reverted back
```
[ ] Yes
[x] No
```
=> fix(router-plugin): revert state back after "RouterCancel" is dispatched

packages/logger-plugin/src/logger.plugin.ts, packages/logger-plugin/tests/helpers/utils.ts, packages/logger-plugin/tests/logger.plugin.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
@splincode @markwhitfeld 
This is very small feature but as you can see at screenshots that the next state should be still logged into console. Given the following code:
```ts
catchError(error => {
ctx.patchState({ counter });
throw error;
})
```
We catch error, patch state and re-throw it. The state WILL be updated, but it will not be logged into console in the current behavior. That small feature fixes it.
=> fix(logger-plugin): print next state even if error was thrown

packages/devtools-plugin/src/devtools.plugin.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #329
```
[ ] Yes
[x] No
```
@splincode @markwhitfeld 
This is very small bugfix for the old #329 issue. In the current behavior our `devtools-plugin` notifies Chrome extension only if everything is OK and no error is thrown. This PR fixes this behavior and notifies Chrome extension to log the state even if error was thrown. Given the following code:
```ts
catchError(error => {
ctx.patchState({ counter });
throw error;
})
``` …
=> fix(devtools-plugin): send action even if error was thrown

packages/logger-plugin/src/action-logger.ts, packages/logger-plugin/src/internals.ts, packages/logger-plugin/src/log-writer.ts, packages/logger-plugin/src/logger.plugin.ts
```
[ ] Bugfix
[ ] Feature
```
The logger plugin has so many responsibilities mixed in one place that it is a real effort to figure out what is happening. This refactoring is in preparation for adding a fix for issue #276,  #213 and #561
```
[ ] Yes
[x] No
```
=>  refactor(logger-plugin): extract ActionLogger for logging action lifecycle

packages/router-plugin/tests/helpers.ts, packages/router-plugin/tests/router-cancel.spec.ts, packages/store/internals/testing/index.ts, packages/store/internals/testing/src/fresh-platform.ts, packages/store/tests/zone.spec.ts
```
[ ] Bugfix
[ ] Feature
```
`freshPlatform` is a wrapper that allows to provide custom platform during testing. It has to be a part of the `@ngxs/store/internals/testing` package to be reusable.
`freshPlatform` is reusable.
```
[ ] Yes
[x] No
```
=> test(store): share "freshPlatform" to make it reusable

integration/jest.integration.config.js, integration/tsconfig.spec.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
When running integration tests Jest should actually use `integration/tsconfig.spec.json` file. Currently it uses the root `tsconfig.json`.
=> build: set the corrent path to the "integration/tsconfig.spec.json"

packages/store/src/configs/messages.config.ts, packages/store/src/execution/dispatch-outside-zone-ngxs-execution-strategy.ts, packages/store/tests/config-validator.spec.ts, packages/store/tests/execution/dispatch-outside-zone-ngxs-execution-strategy.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
Nooped zone is used by people who prefer to run change detection manually in their apps, this requires permanent calls to tick. If the zone is nooped then nothing will happen actually and the user will not benefit from using our default execution strategy, because the zone does nothing basically.
=> fix(store): warn if the zone is not actual "NgZone"

docs/plugins/websocket.md, packages/websocket-plugin/src/public_api.ts, packages/websocket-plugin/src/symbols.ts, packages/websocket-plugin/src/websocket-handler.ts, packages/websocket-plugin/tests/websocket.module.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
@markwhitfeld @splincode 
Gentlemen. This is a super lightweight PR (just 5 lines of code were added). Currently there is no possibility to determine if connection was opened successfully.
The RxJS `WebSocketSubject` has the `openObserver` option that lets us provide a listener for the  events, that occur on the underlying web socket.
Given the following chat application and task:
* show green …
=> feat(websocket-plugin): implement `WebSocketConnected` action

docs/plugins/hmr.md, packages/hmr-plugin/src/hmr-bootstrap.ts, packages/hmr-plugin/src/symbols.ts, packages/hmr-plugin/src/tests/hmr-helpers.ts, packages/hmr-plugin/src/tests/hmr-manager.spec.ts
```
[x] Bugfix
[x] Feature
```
Issue Number: https://github.com/ngxs/store/issues/1347
If during the method of ngOnDestroy the state is deleted before it is saved, we can save the state again after.
```
[ ] Yes
[x] No
```
=> feat(hmr-plugin): add option for persisting state after the root module is disposed

packages/store/src/internal/dispatcher.ts, packages/store/tests/dispatch.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1145 #803 #781 #463 
```
[ ] Yes
[x] No
```
:warning: :warning: **The whole PR description is below** :warning: :warning: 
This PR is a fix for old issues that reported about error handlers that were invoked twice. Let's look at the runtime behavior below:
There is a simple `Increment` action and such state:
```ts
@State({
name: 'counter',
defaults: 0
})
export class CounterState {
@Action(Increment)
increment() {
throw new …
```
=> fix(store): do not re-throw error to the global handler if custom is provided

packages/store/src/actions-stream.ts, packages/store/tests/actions-stream.spec.ts, tsconfig.json
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1149 
```
[ ] Yes
[x] No
```
:exclamation: **This PR is very important and requires views from the outside!** :exclamation: 
---
Let's start with a simple application. That's how I started debugging that `Actions` memory leak. See screenshots below:
So we've got a basic application that has `app-leak` component with bound `ngIf` directive. This component looks as follows:
```ts
@Component({
selector: 'app-leak',
template: ` …
```
=> fix(store): group `Actions` subscriptions to remove memory leak

build/angular-7/package.json, build/angular-7/yarn.lock, build/angular-8/package.json, build/angular-8/yarn.lock, bundlesize.config.json, package.json, yarn.lock
- [N/A] Tests for the changes have been added (for bug fixes / features)
- [N/A] Docs have been added / updated (for bug fixes / features)
This uses ng-packagr >= 5.6.0 (using 5.7.0) which fixes some package linkage issues with ngcc to prepare for angular 9.x and ivy. Without it errors like the following occur on SSR builds with NGXS
```
[ ] Bugfix
[ ] Feature
```
```
ERROR in /Users/pryan/workspaces/@campgroundbooking/portal/node_modules/@ngxs/devtools-plugin/__ivy_ngc …
```
=> build: upgrade ng-packagr for ivy

docs/recipes/cache.md
This is especially useful if the state changes after the snapshot have been called.  For example, if the novel is not in state and you navigate to this component, the state gets updated but you'd only see the change when you refresh the page.
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
=> docs: improve cache recipe example

docs/advanced/life-cycle.md, packages/store/src/internal/internals.ts, packages/store/src/internal/lifecycle-state-manager.ts, packages/store/src/internal/state-context-factory.ts, packages/store/src/internal/state-factory.ts, packages/store/src/public_api.ts, packages/store/src/symbols.ts, packages/store/tests/ngxs-onchanges.spec.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: https://github.com/ngxs/store/issues/749
The method receives a NgxsSimpleChanges object of current and previous property values. This is convenient if we want to dispatch any additional actions when any fields have changed. Called whenever state change.
The main motivation is that this is a convenient hook in order to save states on the server, if we need it. We also have the opportunity to call any third-party services …
=> feat(store): implements ngxsOnChanges

docs/advanced/token.md, packages/store/src/decorators/select/symbols.ts, packages/store/types/tests/selection.lint.ts, packages/store/types/tests/state-token.lint.ts
```
[x] Bugfix
[x] Feature
```
Issue: https://github.com/ngxs/store/issues/875
Correct type checking for selector functions
```
[ ] Yes
[x] No
```
=> feat(store): improved typings for @Select decorator

packages/devtools-plugin/src/devtools.module.ts
```
[x] Bugfix
[ ] Feature
```
```
Compiling @ngxs/devtools-plugin : fesm5 as esm5
Compiling @ngxs/devtools-plugin : fesm2015 as esm2015
Compiling @ngxs/devtools-plugin : esm2015 as esm2015
Error: Error on worker #2: Error: Failed to compile entry-point @ngxs/devtools-plugin due to compilation errors:
node_modules/@ngxs/store/src/module.d.ts(9,22): error TS-996002: Appears in the NgModule.imports of NgxsReduxDevtoolsPluginModule, but could not be resolved to an …
```
=> fix(devtools-plugin): remove `NgxsModule` from imports to ensure Ivy compatibility

CHANGELOG.md, bundlesize.config.json, cypress/ssr/ssr.spec.ts, packages/store/internals/src/memoize.ts, packages/store/src/decorators/select/symbols.ts, packages/store/src/internal/internals.ts, packages/store/src/internal/state-context-factory.ts, packages/store/src/internal/state-factory.ts, packages/store/src/public_api.ts, packages/store/src/store.ts, packages/store/src/utils/selector-utils.ts, packages/store/tests/ensure-store.spec.ts, packages/store/tests/store-isolation.spec.ts
```
[x] Bugfix
[ ] Feature
```
Currently, when the ngxs module is loaded for some states it updates the metadata of those states with the path for those states within the state tree. This is a problem because the metadata should be immutable to prevent one test from affecting the next. Although we cannot remove the behavior with the `path` because it is being used by some plugins, but we can decouple the selectors from this property so that they become deterministic …
=> fix: selectors should be deterministic based on store being used

CHANGELOG.md, packages/store/src/state-token/state-token.ts, packages/store/tests/store-isolation.spec.ts
```
[X] Bugfix
[ ] Feature
```
Currently, there exists an issue with the State Token construct that, if it is used with a sub-state, the selector cannot locate the state within the state tree. This is due to the fact that, when it was implemented, there didn't exist any deterministic construct to determine the location of a state by its' name. PR #1508 added this construct that we are now able to take advantage of.
The selector function for the State …
=> fix: add support for using state tokens in sub states

bundlesize.config.json, packages/store/src/internal/internals.ts, packages/store/src/internal/state-factory.ts, packages/store/src/modules/ngxs-root.module.ts, packages/store/src/public_api.ts, packages/store/src/public_to_deprecate.ts, packages/store/src/state-token/state-token.ts, packages/store/src/store.ts, packages/store/src/utils/selector-utils.ts, packages/store/tests/ensure-store.spec.ts
```
[X] Bugfix
[ ] Feature
```
There was still an aspect of dependency on shared state with selector options. This could cause interactions between tests where the root level selector options differs. This PR resolves this issue.
The selector function is no longer stored in the metadata but rather a factory function for creating selectors given a supplied runtime context. This solves many runtime workarounds that existed for the selector options.
``` …
```
=> fix(store): optimize selector runtime binding

CHANGELOG.md, bundlesize.config.json, docs/concepts/select.md, packages/store/src/decorators/selector/selector.ts, packages/store/src/utils/selector-utils.ts, packages/store/tests/selector.spec.ts
```
[X] Bugfix
[ ] Feature
```
Issue Number: #1340, #1392, #1242, #1143 
There has been a long-standing issue with selectors where they don't work correctly if declared in an arbitrary order. The user was forced to declare referenced selectors in a class before their usage. This was even added to the docs because a solution was not possible... until now...
With the new internal structure of selectors and how they are given a runtime context by the store at the last …
=> fix: selectors should not be declaration order sensitive

CHANGELOG.md, bundlesize.config.json, packages/logger-plugin/src/logger.plugin.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: performance tweak
```
I noticed that the logger was injecting the store on every single dispatched action. 
This is not ideal.
Initialize the store reference lazily only once.
```
[ ] Yes
[x] No
```
=> perf(logger): lazy inject the store once only

docs/advanced/action-handlers.md, docs/advanced/actions-life-cycle.md, docs/advanced/cancellation.md, docs/advanced/composition.md, docs/advanced/lazy.md, docs/advanced/life-cycle.md, docs/advanced/mapped-sub-states.md, docs/advanced/operators.md, docs/advanced/shared-state.md, docs/advanced/sub-states.md, docs/advanced/token.md, docs/concepts/select.md, docs/concepts/state.md, docs/plugins/form.md, docs/plugins/hmr.md, docs/plugins/storage.md, docs/plugins/websocket.md, docs/recipes/cache.md, docs/recipes/style-guide.md, docs/recipes/unit-testing.md
```
[ ] Bugfix
[ ] Feature
```
There have been a number of issues reported where users have not read the requirement for classes to be decorated with `@Injectable()` in Ivy. The docs have not included this, but this would is to the detriment of users starting on Ivy and not knowing the difference.
Issue Number: #1223, #1540, #1535
I added `@Injectable()` to every state class in the docs so that it becomes the new norm.
It should be safe for new and old angular.
```
[ ] …
```
=> docs: add @Injectable above every state class declaration

docs/plugins/hmr.md
Update hmr.md so that \<project-name\> can be seen in the docs
```
[ ] Bugfix
[ ] Feature
```
\<project-name\> does not show in the docs
Fix it so \<project-name\> shows in the docs
```
[ ] Yes
[X] No
```
N/A
=> docs: update hmr.md

packages/router-plugin/src/router.state.ts, packages/router-plugin/tests/router-navigation.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1605
The router-plugin eagerly updates router state _before_ the route is actually activated.  For example, if a route has both guards and resolvers, if the guards succeed but the resolvers fail, ngxs router state _still_ updates even though the route did not activate.  Please see issue for more details.
Current behavior:
1. User clicks a link to a new route
2. Route guards are checked
3. NGXS Router state updates
4. Wait …
=> fix(router-plugin): update state after route successfully activates

docs/recipes/unit-testing.md
- the reset function needs as key value the state name which needs to be reseted
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> doc: better documentation for the reset function

CHANGELOG.md, packages/store/src/internal/state-factory.ts, packages/store/tests/issues/issue-1568-return-empty.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1568 
```
[ ] Yes
[ ] No
```
=> fix: do not cancel actions if action handler completes without emitting

CHANGELOG.md, packages/store/src/operators/of-action.ts, packages/store/types/tests/issues/issue-1561.lint.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1561 
```
[ ] Yes
[x] No
```
=> fix: ofAction* methods should prevent passing anything except of `ActionType`

bundlesize.config.json, packages/store/src/ivy/ensure-state-class-is-injectable.ts, packages/store/src/ivy/ivy-enabled-in-dev-mode.ts
I have noticed that I've added `asObservable()` on the replay subject which creates `new Observable` every time the `ivyEnabledInDevMode` is invoked. That shouldn't be like that since it can slow down things on large codebases and dozens of states.
=> perf: do not create `new Observable()` every time when subscribing to `ivyEnabledInDevMode$`

bundlesize.config.json, docs/plugins/form.md, packages/form-plugin/src/actions.ts, packages/form-plugin/src/directive.ts, packages/form-plugin/src/form.plugin.ts, packages/form-plugin/tests/form.plugin.spec.ts, publication/announcing_ngxs_next/article.md
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
ResetForm action added for form plugin.
=> feat(form-plugin): add reset form action

packages/devtools-plugin/src/devtools.plugin.ts, packages/devtools-plugin/tests/devtools.spec.ts
make action:null before sending to devtools
```
[ X ] Bugfix
[ ] Feature
```
When dispatching an action which payload includes an `action` property, ReduxDevTools logs it as <UNDEFINED>
`action` property will be set to null before sending to devtools to log action correctly
```
[ ] Yes
[ X ] No
```
=> fix(devtools-plugin): actions with "action" property end up logged with <UNDEFINED>

bundlesize.config.json, docs/plugins/hmr.md, packages/hmr-plugin/src/hmr-bootstrap.ts
```
```
improve deprecation note and include workaround example using `storage/plugin`
=> docs(hmr): include workaround using storage-plugin

packages/form-plugin/tests/form.plugin.spec.ts
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Tests
```
There was a test missing from PR #1662 and there was also a bit of cleanup that would improve the tests.
Added missing test, and cleaned up the tests to use setup method as well as the AAA syntax comment sections.
```
[ ] Yes
[X] No
```
=> test(form-plugin): clean up ngxsFormClearOnDestroy tests

CHANGELOG.md, bundlesize.config.json, packages/store/src/decorators/select/select-factory.ts, packages/store/src/internal/state-factory.ts, packages/store/tests/release-resources.spec.ts
```
[x] Bugfix
[ ] Feature
```
#1675 
This is the new behavior after the root module has been destroyed:
```
[ ] Yes
[x] No
```
=> fix: release NGXS resources when the root module gets destroyed

.vscode/launch.json, bundlesize.config.json, integration/app/app.component.html, integration/app/app.component.ts, integration/app/store/store.module.ts, integration/app/store/todos/todos.state.ts, packages/store/src/module.ts, packages/store/src/utils/utils.ts, packages/store/tests/selector.spec.ts, packages/store/tests/utils/utils.spec.ts
```
[X] Bugfix
[ ] Feature
```
Issue Number:  #1683
The values that are set in the options object are supplied by the default options. This behaviour was already partially implemented using `Object.assign`, however that function does not merge deeply. This then affected the `selectorOptions` for the `NgxsStoreModule`, as they are a object inside the `options` object. The new util function `mergeDeep` does basically the same thing as `Object.assign` but also deeply.
``` …
```
=> fix(store): merge options with default options

bundlesize.config.json, packages/store/src/internal/state-factory.ts, packages/store/tests/store.spec.ts
```
[X] Bugfix
[ ] Feature
```
If a selector is used to retrieve state from a state that has not yet loaded then, for that specific observable, the value does not get updated once the state is loaded, but it always returns `undefined`.
Issue Number: #1522 
The selector will return the correct values once the state is loaded.
```
[ ] Yes
[x] No
```
=> fix(store): faulty select if requested before state added

CHANGELOG.md, integrations/hello-world-ng11-ivy/bundlesize.config.json, packages/router-plugin/src/router.state.ts
Removing `isAngularInTestMode()` from the router plugin will allow us to tree-shake this function completely.
=> perf(router-plugin): tree-shake `isAngularInTestMode()`

CHANGELOG.md, bundlesize.config.json, packages/devtools-plugin/src/devtools.plugin.ts, packages/devtools-plugin/src/symbols.ts, packages/devtools-plugin/tests/devtools-custom.spec.ts, packages/devtools-plugin/tests/devtools-errors.spec.ts, packages/devtools-plugin/tests/devtools.spec.ts
=> fix(devtools-plugin): do not connect when `disabled` is truthy

CHANGELOG.md, bundlesize.config.json, integrations/hello-world-ng11-ivy/bundlesize.config.json, integrations/hello-world-ng12-ivy/bundlesize.config.json, package.json, packages/store/src/internal/state-factory.ts, packages/store/tests/action.spec.ts
```
[X] Bugfix
[ ] Feature
```
There currently exists an issue where a user could mistakenly return an observable from an async method and the returned observable will not be subscribed to, and will not determine the completion event of the original action.
A similar situation exists (although not as impactful) where a promise is returned from an observable. For example, if the user used the `map` rxjs pipe, but declared the mapper function as `async (value) => { …
=> fix(store): handle mixed async scenarios for action handlers

CHANGELOG.md, bundlesize.config.json, integrations/hello-world-ng11-ivy/bundlesize.config.json, packages/store/src/internal/state-factory.ts, packages/store/tests/action.spec.ts, packages/store/tests/dispatch.spec.ts
```
[X] Bugfix
[ ] Feature
```
Currently there is a slightly unexpected order of events when one in-process action is cancelled in favor of another.
The handler for the second action is executed before the observable for the first actions is unsubscribed.
This can lead to subtle issues, especially when implementing an optimistic update strategy.
After this PR, the first action's observable will be unsubscribed (and cancelled) before the second action …
=> fix(store): cancel uncompleted should unsubscribe before next

CHANGELOG.md, bundlesize.config.json, integrations/hello-world-ng11-ivy/bundlesize.config.json, integrations/hello-world-ng12-ivy/bundlesize.config.json, packages/storage-plugin/src/storage.plugin.ts, packages/storage-plugin/tests/issues/issue-restore-state-only-if-key-matches.spec.ts
```
[x] Bugfix
[ ] Feature
```
This plugin is reacting to the `InitState` event as well as any `UpdateState` events.
When state is loaded lazily, it triggers an `UpdateState` event that passes along the states being added `addedStates`.  Each time an `UpdateState` event is triggered, it causes the state to be restored for each key defined in storage-plugin.  In cases where there are multiple lazily loaded state, this causes multiple `setState` actions to be triggered, …
=> fix(storage-plugin): only restore state if key matches addedStates

CHANGELOG.md, packages/store/src/actions-stream.ts, packages/store/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(store): expose `ActionContext` and `ActionStatus`

.circleci/config.yml
```
[ ] Bugfix
[ ] Feature
```
Related PR: #1778
Temporarily disable the integration tests that were messing up the dev publish
```
[ ] Yes
[x] No
```
=> build: temporarily skip faulty integration test in circle ci

docs/plugins/storage.md
Remove outdated `key` method.
Closes #1685
=> docs: update `StorageEngine` section

docs/concepts/state.md
Currently the docs for state mention state operators being a WIP, with a link to the github issue for that ticket. I removed that content and replaced it with "You can find more details in our state operators documentation", where "state operators" is a link to that documentation page.
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> docs(store): Add state operator link to state docs

docs/plugins/form.md
`Controls` prop gives us an object that throws an error when using that prop for the `NgFor` directive, since Object is not iterable.
Fixes #1733
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(docs): replace controls prop with value

bundlesize.config.json, integrations/hello-world-ng11-ivy/bundlesize.config.json, integrations/hello-world-ng12-ivy/src/app/__snapshots__/issue-1801-select-within-constructor.spec.ts.snap, integrations/hello-world-ng12-ivy/src/app/issue-1801-select-within-constructor.spec.ts, integrations/hello-world-ng13-ivy/src/app/__snapshots__/issue-1801-select-within-constructor.spec.ts.snap, integrations/hello-world-ng13-ivy/src/app/issue-1801-select-within-constructor.spec.ts, packages/store/internals/src/decorator-injector-adapter.ts, packages/store/internals/src/index.ts, packages/store/src/decorators/select/select.ts
Hey, this is the fastest solution I came with. I don't have other ideas. I'm opening a PR so we can discuss the implementation and I'm open to other ideas!
=> fix(store): allow `@Select()` decorated properties to be accessed within constructors

packages/store/operators/src/append.ts, packages/store/operators/src/compose.ts, packages/store/operators/src/iif.ts, packages/store/operators/src/index.ts, packages/store/operators/src/insert-item.ts, packages/store/operators/src/patch.ts, packages/store/operators/src/update-item.ts, packages/store/operators/src/utils.ts, packages/store/operators/tests/update-item.spec.ts, packages/store/types/tests/state-operator.lint.ts, packages/store/types/tests/state-operators.append.lint.ts, packages/store/types/tests/state-operators.iif.lint.ts, packages/store/types/tests/state-operators.insert-item.lint.ts, packages/store/types/tests/state-operators.remove-item.lint.ts, packages/store/types/tests/state-operators.update-item.lint.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(store): do not infer T from argument to patch

packages/store/src/selectors/create-selector.util.ts, packages/store/src/selectors/selector-types.util.ts
```
[ ] Bugfix
[x] Feature
```
The current `createSelector` uses `any` in its typing and does not calculate the return type correctly.
This PR is the first step to introducing an improvement to those typings.
The improved `createSelector` is added here without exporting it to enable some other concurrent work in other PRs.
There will be a separate PR that adds the type tests for this as well as replacing the previous loosely typed version.
```
[ ] Yes
[X] No
```
=> chore(store): add initial version of new strongly typed createSelector

.eslintignore, angular.json, jest.config.js
```
[x] Bugfix
[ ] Feature
```
`__name__.spec.ts` are included when jest executes unit tests which leads to failures.
`__name__.spec.ts` are checked by eslint an tslint.
`__name__.spec.ts` are excluded when jest executes unit tests.
`__name__.spec.ts` are excluded from eslint and tslint checks.
```
[ ] Yes
[x] No
```
=> test(store): fix jest and linter configs - update ignored patterns

CHANGELOG.md, bundlesize.config.json, packages/store/src/internal/state-operations.ts, packages/store/src/symbols.ts
```
```
```
[ ] Yes
[x] No
```
=> perf(store): tree-shake `deepFreeze`

CHANGELOG.md, packages/store/internals/src/angular.ts, packages/store/tests/utils/angular.spec.ts
@markwhitfeld I've noticed that this function doesn't work in ESP app because there's no `MockNgModuleResolver` anymore (the `@angular/compiler/testing`) just doesn't export anything now. Thee `MockNgModuleResolver` was available before the VE support has been removed.
We couldn't see that in NGXS repository since our packages are version 9.
=> fix(store): be more explicit when checking if Angular is in test mode

package.json, packages/store/schematics/factories/ng-add/ng-add.factory.spec.ts, packages/store/schematics/factories/ng-add/ng-add.factory.ts, packages/store/schematics/factories/ng-add/ng-add.schema.d.ts, packages/store/schematics/factories/ng-add/schema.json, packages/store/schematics/utils/common/lib.config.ts, yarn.lock
```
[ ] Bugfix
[x] Feature
```
Issue Number: #769
The `ng-add` schematic was partially improved towards meeting the goal describe in [the document](https://docs.google.com/document/d/1WNsDt7aLxHrQwq0DHJ9mZefKGiDkdVvIpNfsoTggENA/edit#heading=h.iyi6qkxfo6c5)
```
[ ] Yes
[x] No
```
=> feat(ngadd): improve the ngxs ng-add schema and factory, add unit test

.github/workflows/release.yml, .github/workflows/trunk.yml
```
[ ] Bugfix
[ ] Feature
```
Currently the publish jobs are triggered always, in forked repos as well.
The publish jobs are triggered only if the repo owner is `ngxs`.
The publish jobs are not triggered from forks.
```
[ ] Yes
[x] No
```
=> ci(publish): check the repo owner before executing publish steps

CHANGELOG.md, packages/store/src/decorators/state.ts, packages/store/src/internal/state-factory.ts, packages/store/src/ivy/ivy-enabled-in-dev-mode.ts
=> fix(store): do not check if the state class is injectable within the decorator since the `ɵprov` will not exist in JIT mode

packages/store/src/store.ts, packages/store/tests/execution/dispatch-outside-zone-ngxs-execution-strategy.spec.ts, packages/store/tests/issues/issue-1880-last-select-value.spec.ts, packages/store/tests/zone.spec.ts
Issue: #1880 
I don't know if there're other ways to fix that issue since using `refCount()` just makes the stream cold when there're no observers, but `publishReplay` buffers the last received value. See the issue and unit test.
The `shareReplay` increases the number of ticks by 1, but fixes the issue.
=> fix(store): do not use `refCount()` since it makes the stream cold

.github/workflows/pr-validation.yml, .github/workflows/release.yml, .github/workflows/trunk.yml
```
[ ] Bugfix
[ ] Feature
```
A Bundlemon failure fails the workflow.
We should allow for a Bundlemon Failure to be approved by the reviewer, resulting in a successful workflow.
PS. I also took the opportunity to remove the pointless node version dimension of the job matrixes.
=> ci: add process for accepting bundlemon differences

CHANGELOG.md, packages/store/src/symbols.ts
Closes #1689
This commit updates the signature of `NgxsOnInit` and `NgxsAfterBootstrap` interfaces. The `ctx` parameter was marked as optional initially by some reason. But it's never optional since we pass the `ctx` parameter. This isn't a breaking change.
=> fix(store): remove `?` from `ctx` parameter of lifecycle hooks since they are never undefined

CHANGELOG.md, packages/form-plugin/src/directive.ts, packages/form-plugin/tests/issues/issue-1822-multiple-ngxs-form-bindings.spec.ts
Issue: #1822 
I'm unsure if there's another way to fix this issue because `valueChanges` continuously emits a new object (with a new reference), which means just adding `distinctUntilChanged()` isn't enough.
I've been thinking of potential breaking changes with this change. Since binding 2 `ngxsForm` is impossible for now, we can imagine that people are binding `ngxsForm` only once. So if the form value is updated outside with the same value and we're not dispatching any actions - this probably might not break anything.
=> fix(form-plugin): prevent actions infinite loop with multiple `ngxsForm` directives

packages/router-plugin/tests/helpers.ts, packages/router-plugin/tests/issues/issue-1293.spec.ts, packages/router-plugin/tests/issues/issue-1407.spec.ts, packages/router-plugin/tests/router-cancel.spec.ts, packages/router-plugin/tests/router-data-resolved.spec.ts, packages/router-plugin/tests/router-navigation.spec.ts, packages/router-plugin/tests/router-state-cleanup.spec.ts, packages/router-plugin/tests/router.plugin.spec.ts
No functional changes, only cleans up navigation warnings, since it makes a lot of noise in the console.
=> test(router-plugin): silence navigation warnings

CHANGELOG.md, packages/router-plugin/src/router.state.ts
Issue: #1898
We initially added this check when trying to fix router + storage plugins integration.
We had an open issue related to this (https://github.com/ngxs/store/issues/1204), but I've closed it since I verified the issue is not reproducible anymore with the latest NGXS version. The issue was reproducible with the `3.5.0` version (which was used in the reproducible example). I have upgraded NGXS and removed the `checkInitialNavigationOnce` method, and the behavior was the same as expected (the issue still wasn't reproducible).
=> fix(router-plugin): prevent router overriding valid navigation

CHANGELOG.md, packages/store/src/store.ts, packages/store/tests/issues/issue-1728-dispatch-from-select-subscriber.spec.ts, tsconfig.spec.json
Issue: #1728 
<s>Note: `do not emit old values from the state` is a wrong commit name, I just haven't found anything meaningful, this should be renamed.</s>
I've updated `tsconfig.spec.json` to stop warning on unused locals, because it's a pain writing unit tests with these options enabled.
=> fix(store): avoid incorrectly ordered state observable events

CHANGELOG.md, packages/store/src/internal/state-factory.ts
Issue: #1921 
We can safely use `isObservable` since it already does `instanceof Observable`, but also checks for `obj.lift && obj.subscribe` to be functions.
=> fix(store): use `isObservable` to test whether actions return an observable

CHANGELOG.md, packages/storage-plugin/src/storage.plugin.ts, packages/storage-plugin/tests/issues/issue-1916-key-state-notation.spec.ts
Issue: #1916 
This initially was the issue since I didn't even remember that we allow having dot notation in keys, e.g., `key: ['myState.myProp']`. The current fix handles this case when `key` contains dot notation.
=> fix(storage-plugin): do not skip deserialization for keys with dot notation

CHANGELOG.md, packages/form-plugin/tests/issues/issue-1567-ngxs-onchanges-hook-with-plugin.spec.ts, packages/store/src/internal/internals.ts, packages/store/src/internal/lifecycle-state-manager.ts, packages/store/src/internal/state-context-factory.ts, packages/store/tests/ngxs-onchanges.spec.ts
=> fix(store): call `ngxsOnChanges` whenever state changes (even through plugins)

CHANGELOG.md, packages/store/src/internal/dispatcher.ts, packages/store/src/internal/error-handler.ts, packages/store/src/internal/lifecycle-state-manager.ts, packages/store/tests/dev-mode.spec.ts, packages/store/tests/dispatch.spec.ts, packages/store/tests/issues/issue-1687-inject-store-inside-error-handler.spec.ts, packages/store/tests/issues/issue-1691-error-handling.spec.ts
=> fix(store): do not delegate errors to `ErrorHandler` if users catch them manually

package.json, packages/store/tests/execution/dispatch-outside-zone-ngxs-execution-strategy.spec.ts, packages/store/tests/zone.spec.ts, yarn.lock
Fixes cypress postinstall error "Cannot find any-observable implementation nor global.Observable".
=> build: bump RxJS version to repair Cypress postinstall

CHANGELOG.md, docs/plugins/devtools.md, packages/devtools-plugin/src/symbols.ts
- [x ] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
- [ x] Tests for the changes have been added (for bug fixes / features)
- [ x] Docs have been added / updated (for bug fixes / features)
```
[ ] Bugfix
[x] Feature
```
User unable to pass options to the redux dev tools because we don't have all options described in NgxsDevtoolsOptions interface
Added new [option …
=> feat(devtools-plugin): add new options to the `NgxsDevtoolsOptions` interface

CHANGELOG.md, docs/plugins/router.md, packages/router-plugin/src/public_api.ts, packages/router-plugin/src/router.actions.ts, packages/router-plugin/src/router.module.ts, packages/router-plugin/src/router.state.ts, packages/router-plugin/src/symbols.ts, packages/router-plugin/tests/issues/issue-1718-url-recognition.spec.ts, packages/router-plugin/tests/router-navigation.spec.ts
Issues: #1605 #1718
I finally got my hands to the router plugin. Its implementation was initially tied from the ngrx router package. I had to sync the implementation again.
I can't push my changes separately as they're all part of the same fix. This fixes old issues and adds new actions + router option (like navigation timing).
=> feat(router-plugin): provide more actions and navigation timing option

CHANGELOG.md, packages/store/src/actions-stream.ts, packages/store/src/internal/custom-rxjs-subjects.ts, packages/store/src/internal/state-stream.ts, packages/store/src/store.ts, packages/store/tests/actions-stream.spec.ts, packages/store/tests/issues/issue-1568-return-empty.spec.ts, packages/store/tests/issues/issue-1603-no-type-property-on-the-action.spec.ts, packages/store/tests/issues/issue-1687-inject-store-inside-error-handler.spec.ts, packages/store/tests/issues/issue-1691-error-handling.spec.ts, packages/store/tests/issues/issue-1880-last-select-value.spec.ts, packages/store/tests/issues/issue-1976-select-once-after-dispatch.spec.ts, packages/store/tests/issues/issue-759-dispatching-empty.spec.ts, packages/store/tests/issues/issue-933-selectors-causing-ticks.spec.ts
```
[x] Bugfix
[ ] Feature
```
Currently, if an action is dispatched and, in the subscription to the observable returned by the `dispatch` call, we use a `selectOnce` then the value emitted is the value from the state before the action was dispatched.
Issue Number: #1976 
The `queueScheduler` from rxjs does not honor the "synchronous" operation stated in the docs, so this has been removed from the stream constructed for selectors, and the state stream now uses the …
=> fix(store): avoid delayed updates from state stream

CHANGELOG.md, docs/plugins/form.md, packages/form-plugin/src/directive.ts, packages/form-plugin/tests/form.plugin.spec.ts, packages/form-plugin/tests/issues/issue-1590-update-form-value-primitive.spec.ts, packages/form-plugin/tests/issues/issue-1822-multiple-ngxs-form-bindings.spec.ts, packages/form-plugin/tests/property-path.spec.ts
The `ngxsFormDebounce` is a static binding for now which means we're not watching its changes. We read it only once and provide to `debounceTime`. The change allows providing `ngxsFormDebounce` as a string, and not as a number so we extend possible values to be provided:
```html
<form [ngxsFormDebounce]="300">...</form>
<form ngxsFormDebounce="300">...</form>
```
=> feat(form-plugin): allow `ngxsFormDebounce` to be string

packages/store/tests/issues/state-stream-order.spec.ts
This PR adds a test that reproduces the situation where the state stream update is not immediately available after the `patchState` call. This documents a bug that is being investigated and will be fixed very soon.
=> test(store): add unit tests to reproduce state value is not immediately set but queued up

CHANGELOG.md, docs/plugins/storage.md, packages/storage-plugin/src/internals/final-options.ts, packages/storage-plugin/src/storage.module.ts, packages/storage-plugin/src/symbols.ts, packages/storage-plugin/tests/issues/issue-598-storage-engine-per-key.spec.ts
This commit updates the signature of the `StorageEngine` interface
and removes unnecessary properties that are not being used by the storage
plugin. The properties `length`, `removeItem`, and `clear` have been removed.
This change makes it easier to maintain storage engines that implement the
interface because only the necessary properties will be required. It is important
to note that this change is not considered a breaking change since properties are
being removed rather than added.
=> fix(storage-plugin): require only `getItem` and `setItem` on engines

CHANGELOG.md, packages/form-plugin/src/actions.ts, packages/router-plugin/src/router.actions.ts, packages/store/src/actions/actions.ts, packages/websocket-plugin/src/symbols.ts
This commit replaces type getters with property declarations like
`static type = '...'`. The `get type()` was required a long time ago
to maintain backward compatibility between TypeScript 2 and 3 versions.
However, this is no longer necessary.
=> refactor(*): replace `get type()` with `type =` in actions

packages/storage-plugin/internals/ng-package.json, packages/storage-plugin/internals/src/final-options.ts, packages/storage-plugin/internals/src/index.ts, packages/storage-plugin/internals/src/storage-key.ts, packages/storage-plugin/internals/src/symbols.ts, packages/storage-plugin/src/engines.ts, packages/storage-plugin/src/internals.ts, packages/storage-plugin/src/public_api.ts, packages/storage-plugin/src/storage.module.ts, packages/storage-plugin/src/storage.plugin.ts, packages/storage-plugin/tests/issues/issue-1146-invalid-rehydration.spec.ts, packages/storage-plugin/tests/issues/issue-1857-update-for-lazy-state.spec.ts, packages/storage-plugin/tests/storage.plugin.spec.ts, tsconfig.base.json
This commit exposes some of the storage plugin internals through a subpackage, following a similar approach to how router plugin internals are exposed. These internals are necessary to expose if someone wishes to extend the storage engine's behavior. For example, to check for the default state key `@@STATE` or to use helper functions like extracting string keys.
=> fix(storage-plugin): expose storage plugin internals privately through subpackage

CHANGELOG.md, packages/websocket-plugin/src/providers.ts, packages/websocket-plugin/src/symbols.ts, packages/websocket-plugin/src/websocket-handler.ts, packages/websocket-plugin/src/websocket.module.ts
This commit updated the WebSocket handler implementation and switched to
using the native `WebSocket` directly, instead of relying on `rxjs/webSocket`.
The RxJS WebSocket implementation can be cumbersome when it comes to handling
socket events and lacks simplicity. By handling socket events manually, we avoid
the need to use the RxJS implementation.
=> refactor(websocket-plugin): get rid off `rxjs/webSocket` and use `WebSocket` directly

packages/form-plugin/src/directive.ts, packages/router-plugin/src/router.state.ts, packages/store/src/internal/lifecycle-state-manager.ts
This commit updates all `destroy$` subjects to be replayed subjects for consistency across implementations. This change ensures that no more subscriptions occur after any injectee is destroyed.
=> refactor: use `ReplaySubject` for take until notifiers

packages/logger-plugin/tests/helpers/setup-with-logger.ts, packages/router-plugin/tests/issues/issue-1407.spec.ts, packages/storage-plugin/internals/src/storage-key.ts, packages/store/internals/src/index.ts, packages/store/internals/src/symbols.ts, packages/store/internals/testing/src/symbol.ts, packages/store/src/decorators/state.ts, packages/store/src/internal/internals.ts, packages/store/src/internal/state-factory.ts, packages/store/src/module.ts, packages/store/src/selectors/selector-types.util.ts, packages/store/src/standalone-features/feature-providers.ts, packages/store/src/standalone-features/provide-states.ts, packages/store/src/standalone-features/provide-store.ts, packages/store/src/standalone-features/root-providers.ts, packages/store/src/symbols.ts, packages/store/tests/action-handler.spec.ts, packages/store/tests/action.spec.ts, packages/store/tests/selector.spec.ts, packages/store/tests/state.spec.ts, packages/store/tests/store-isolation.spec.ts
This commit relocates keys used for storing metadata and options on state classes to the internals package. It can now be exposed to plugin authors who need to retrieve metadata from state classes and prefer a stable key.
=> fix(store): expose keys which are used to store metadata privately

docs/SUMMARY.md, docs/concepts/actions.md, docs/concepts/state.md, docs/concepts/store.md, docs/introduction/installation.md, docs/introduction/schematics.md, docs/introduction/starter-kit.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> docs: introduce schematics

CHANGELOG.md, packages/store/src/configs/messages.config.ts, packages/store/src/internal/lifecycle-state-manager.ts, packages/store/tests/issues/state-initialization-order.spec.ts
This commit adds a `console.error` when the `UpdateState` is dispatched before the `InitState`. This typically indicates that the state initialization order is invalid and must be updated to ensure that states are initialized in the correct order. The incorrect order may prevent `ngxsOnInit` from being called on feature states or lead to other unpredictable errors.
=> fix(store): show error when state initialization order is invalid

CHANGELOG.md, packages/store/src/configs/messages.config.ts, packages/store/src/internal/lifecycle-state-manager.ts, packages/store/tests/issues/state-initialization-order.spec.ts
In this commit, the logged error has been improved to contain feature states, that were added, before the store initialization is complete.
=> fix(store): log feature states added before store is initialized

packages/form-plugin/README.md
```
[ ] Bugfix
[ ] Feature
```
The npm package is `@ngxs/form-plugin` but the title in README is `@ngsx/forms-plugin` with an `s`
The `s` is removed so the title matches the npm package
```
[ ] Yes
[x] No
```
=> docs(form-plugin): npm package title and title of README mismatch

.gitignore, packages/store/operators/src/patch.ts, packages/store/operators/tests/patch.spec.ts
Changed patch operator not fail when the existing value is null by using a null save access to the key of the object
fixes #2063
```
[x] Bugfix
[ ] Feature
```
When the existing value of the patch operator is null/undefined it causes a key access error
Issue Number: #2063 
Does not throw an error if existin is null/undefined
```
[ ] Yes
[x] No
```
=> fix(store): patch operator must handle existing nulls

.codeclimate.yml, packages/store/jest.config.js, packages/store/schematics/src/ng-add/add-declaration.ts, packages/store/schematics/src/ng-add/ng-add.factory.spec.ts, packages/store/schematics/src/ng-add/ng-add.factory.ts, packages/store/schematics/src/utils/config.ts, packages/store/schematics/src/utils/ng-utils/README.md, packages/store/schematics/src/utils/ng-utils/ast-utils.ts, packages/store/schematics/src/utils/ng-utils/ng-ast-utils.ts, packages/store/schematics/src/utils/ng-utils/project.ts, packages/store/schematics/src/utils/ng-utils/standalone/app_config.ts, packages/store/schematics/src/utils/ng-utils/standalone/code_block.ts, packages/store/schematics/src/utils/ng-utils/standalone/index.ts, packages/store/schematics/src/utils/ng-utils/standalone/rules.ts, packages/store/schematics/src/utils/ng-utils/standalone/util.ts, packages/store/schematics/src/utils/project.ts
```
[ ] Bugfix
[x] Feature
```
Adding support for standalone APIs in schematics
With this PR `ng-add` will be able to add NGXS plugins both to root module as modules and to app.config as provider functions.
Please note that there's a new folder `packages/store/schematics/src/utils/ng-utils`. It contains files that were copied from the `@schematics/angular@16.2` package. It contains very convenient utils that allow adding declarations both in standalone and regular …
=> feat(store): add support for standalone APIs in schematics

integration/project.json
changes the old `build-app` target to `build`
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> refactor: integration app serve targets

packages/store/schematics/src/starter-kit/files/store/auth/auth.state.spec.ts__template__, packages/store/schematics/src/starter-kit/files/store/auth/auth.state.ts__template__, packages/store/schematics/src/starter-kit/files/store/dashboard/states/dictionary/dictionary.state.spec.ts__template__, packages/store/schematics/src/starter-kit/files/store/dashboard/states/dictionary/dictionary.state.ts__template__, packages/store/schematics/src/starter-kit/files/store/dashboard/states/user/user.state.spec.ts__template__, packages/store/schematics/src/starter-kit/files/store/dashboard/states/user/user.state.ts__template__, packages/store/schematics/src/state/files/__name__.state.spec.ts__template__, packages/store/schematics/src/state/files/__name__.state.ts__template__, packages/store/schematics/src/store/files/__name__.state.spec.ts__template__, packages/store/schematics/src/store/files/__name__.state.ts__template__, packages/store/schematics/src/utils/versions.json
This fix replaces the deprecated `async` testing function with an async/await, in the unit tests that are generated via the schematics.
It also adds the `@Injectable` decorator in the generated via the schematics state files
=> fix(schematics): replace the deprecated api in the unit tests and add a missing decorator

CHANGELOG.md, packages/store/src/standalone-features/provide-store.ts
We have a check that ensures states are initialized in the correct order and that the `UpdateState` action shouldn't be dispatched before the `InitState` action. This code updates the order of environment providers to place features at the end. As a result, the root environment initializer runs earlier, dispatching the `InitState` action.
=> fix(store): ensure features are initialized after root state

packages/store/schematics/src/actions/files/__name__.actions.ts__template__, packages/store/schematics/src/starter-kit/files/store/auth/auth.actions.ts__template__, packages/store/schematics/src/starter-kit/files/store/auth/auth.state.ts__template__, packages/store/schematics/src/starter-kit/files/store/dashboard/states/dictionary/dictionary.actions.ts__template__, packages/store/schematics/src/starter-kit/files/store/dashboard/states/dictionary/dictionary.state.ts__template__, packages/store/schematics/src/starter-kit/files/store/dashboard/states/user/user.actions.ts__template__, packages/store/schematics/src/starter-kit/files/store/dashboard/states/user/user.state.ts__template__, packages/store/schematics/src/state/files/__name__.state.ts__template__, packages/store/schematics/src/state/state.factory.ts, packages/store/schematics/src/store/files/__name__.actions.ts__template__, packages/store/schematics/src/store/files/__name__.state.ts__template__, packages/store/schematics/src/store/store.factory.ts
When we use the schematics and we provide a camelCase or a PascalCase name to `state` or a `store` , the file name generation is not dasherized.
**Store** 
_Before_
> ng generate @ngxs/store:store --path src/app --name MyStore
CREATE src/app/my-store/`MyStore`.actions.ts 
CREATE src/app/my-store/`MyStore`.state.spec.ts
CREATE src/app/my-store/`MyStore`.state.ts 
_After_
> ng generate @ngxs/store:store --path src/app --name MyStore
CREATE src/app/my-store/`my-store`.actions.ts
CREATE src/app/my-store/`my-store`.state.spec.ts 
CREATE src/app/my-store/`my-store`.state.ts
**State**
_Before_
> ng generate @ngxs/store:state --path src/app --name MyState
CREATE src/app/my-state/`MyState`.state.spec.ts
CREATE src/app/my-state/`MyState`.state.ts
_After_
> ng generate @ngxs/store:state --path …
=> fix(schematics): dasherize the state and store file name

CHANGELOG.md, packages/store/src/internal/state-factory.ts, yarn.lock
We need to use `isPromise` instead of checking whether `result instanceof Promise`.
In zone.js patched environments, `global.Promise` is the `ZoneAwarePromise`. Some APIs,
which are likely not patched by zone.js for certain reasons, might not work with `instanceof`.
For instance, the dynamic import returns a native promise (not a `ZoneAwarePromise`), causing
this check to be falsy.
=> fix(store): change `instanceof Promise` to `isPromise` to allow any promisable object

.circleci/config.yml
This should have been removed in the migration PR, but I probably missed it. This should re-enable publish on master.
=> ci: remove `integration_ng15_tests` job

docs/plugins/storage.md, integration/app/app.config.ts, integrations/hello-world-ng16/src/app/store/store.module.ts, integrations/hello-world-ng17/src/app/store/store.module.ts, packages/storage-plugin/internals/src/final-options.ts, packages/storage-plugin/internals/src/symbols.ts, packages/storage-plugin/src/internals.ts, packages/storage-plugin/src/storage.module.ts, packages/storage-plugin/tests/issues/issue-1146-invalid-rehydration.spec.ts, packages/storage-plugin/tests/issues/issue-1634-resolve-state-name.spec.ts, packages/storage-plugin/tests/issues/issue-1857-update-for-lazy-state.spec.ts, packages/storage-plugin/tests/issues/issue-1916-key-state-notation.spec.ts, packages/storage-plugin/tests/issues/issue-598-storage-engine-per-key.spec.ts, packages/storage-plugin/tests/issues/issue-restore-state-only-if-key-matches.spec.ts, packages/storage-plugin/tests/storage.plugin.spec.ts
This commit updates the implementation of the register signature for the storage plugin.
It now always requires `options` to be provided. We want to ensure clarity regarding the
states that we're going to serialize. When no `options` are provided, we implicitly provide
the `@@STATE` key, which defines that all states should be serialized. This implementation
doesn't compromise extendability because we implicitly rely on the internal mechanism that
transforms options. We should always require options to be provided and require developers
to specify serializable states explicitly.
This would allow us to have feature states because the feature registration mechanism would
also know if the user explicitly specified all states to be serialized at the root level or not.
**Note:** This change is …
=> feat(storage-plugin): require explicit options when providing storage plugin

packages/store/src/internal/internals.ts
This commit enhances the `compliantPropGetter` function's implementation. The prop getter is heavily utilized in NGXS. I noticed that the function unnecessarily copies `paths`. It now returns a function that accepts an object as a parameter and attempts to select a property deeply. We've replaced the use of `reduce` with a single for-loop, making it simpler. Though it doesn't significantly impact size, there's only a minor difference in production bundle size.
Regarding performance, I checked the `perf.link` service and got the following results:
- Old compliant prop getter: 120,410 ops/s
- New compliant prop getter: 220,480 ops/s
I generated a deeply nested object and set my CPU slowdown to 6x. The new implementation is only 30% faster, but it's reasonable to have a slightly faster …
=> perf(store): improve compliant prop getter

packages/store/src/internal/dispatcher.ts, packages/store/src/internal/error-handler.ts, packages/store/src/store.ts, packages/store/tests/dispatch.spec.ts, packages/store/types/tests/dispatch.lint.ts
This commit updates all `dispatch` signatures to return `Observable<void>`. Initially, the signature was intended to be `void`, but historically, it was returning `Observable<any>`, where `any` represents the state snapshot.
This is a breaking change. We've been delaying this fix for years, but now all the necessary changes should finally be made to allow us to progress with the NGXS code itself. It's especially important to clean up old planned todos as well.
=> fix(store): `dispatch` return observable should be `<void>`

packages/store/src/selectors/selector-utils.ts, packages/store/src/store.ts, packages/store/src/symbols.ts, packages/store/tests/select-signal.spec.ts, packages/store/tests/select.spec.ts, packages/store/tests/selector.spec.ts
This commit updates the `suppressErrors` configuration property to default to falsy.
Consequently, if the selector function throws a type error (such as when accessing a
property unsafely), the error will now be thrown.
`selectSnapshot` will throw synchronously, while errors from `select` will be thrown
asynchronously because the RxJS error reporter operates within a `setTimeout`.
We log errors in development mode to assist developers in identifying selectors that have thrown.
This change is breaking and is part of the v4 release preparation.
=> fix(store): enable throwing errors from selectors by default

integration/app/store/todos/todo/todo.state.ts, package.json, packages/hmr-plugin/src/internal/hmr-lifecycle.ts, packages/hmr-plugin/src/internal/hmr-state-context-factory.ts, packages/store/ng-package.json, packages/store/package.json, packages/store/src/internal/internals.ts, packages/store/src/internal/state-context-factory.ts, packages/store/src/symbols.ts, yarn.lock
This commit modifies the return value of `StateContext.getState` from `<T>` to `ReadonlyDeep<T>`.
The `ReadonlyDeep` type is provided by the `type-fest` package, which is now included in the
dependencies of `@ngxs/store` and will be installed automatically with it.
This change is necessary because `getState` should return an immutable object, and users should
not have any reason to directly modify it.
Please note that this change is breaking and is part of the v4 release preparation.
=> fix(store): `ctx.getState` should return `DeepReadOnly<>`

packages/store/src/internal/internals.ts, packages/store/src/internal/state-context-factory.ts, packages/store/src/store.ts, packages/store/src/symbols.ts, packages/store/types/tests/dispatch.lint.ts
This commit modifies the signatures of `setState` and `patchState` to return `<void>`. Previously, they were returning `<T>`, which was historically a mistake. This change also impacts the `Store.reset` method since it utilizes `setState`, resulting in `Store.reset` now also returning `<void>`.
`setState` is designed to update the state, and as such, the method itself should not generate a return value. Users should utilize `getState` to retrieve the latest value accordingly.
=> fix(store): `setState` and `patchState` should both return `<void>`

integration/app/app.component.ts, integration/app/list/list.component.ts, integrations/hello-world-ng16/src/app/app.component.ts, integrations/hello-world-ng16/src/app/store/counter/counter.state.ts, integrations/hello-world-ng17/src/app/app.component.ts, integrations/hello-world-ng17/src/app/store/counter/counter.state.ts, packages/router-plugin/src/public_api.ts, packages/router-plugin/src/router.state.ts, packages/router-plugin/tests/router-data-resolved.spec.ts, packages/store/src/store.ts, packages/store/types/tests/selection.lint.ts, packages/store/types/tests/state-token.lint.ts
This commit modifies the signatures of `select`, `selectOnce`, and `selectSnapshot` to exclusively accept typed selectors. They should not permit acceptance of anything lacking type information, such as state classes (`select(MyState)`), strings, or anonymous functions. Only state tokens and selectors are now allowed.
This adjustment also impacts the router plugin, as it previously used `RouterState` for selecting snapshots, which is no longer allowed. Consequently, we introduced `ROUTER_STATE_TOKEN` as the replacement for selections involving `RouterState`.
=> fix(store): `select,selectOnce,selectSnapshot` should only accept typed selector

packages/router-plugin/tests/issues/issue-1718-url-recognition.spec.ts, packages/store/internals/testing/tests/ngxs.setup.spec.ts, packages/store/src/decorators/selector/selector.ts, packages/store/src/selectors/selector-utils.ts, packages/store/src/symbols.ts, packages/store/tests/helpers/todo.state.ts, packages/store/tests/select-signal.spec.ts, packages/store/tests/selector.spec.ts, packages/store/tests/zone.spec.ts
This commit updates the `injectContainerState` configuration property to default to false. This change will affect the behavior of `@Selector()`s, as they will no longer receive the container state as the first argument if there are any selectors in the list.
The current behavior is as follows:
```ts
@State()
class NotificationsState {
@Selector()
static getNotifications(state: NotificationsStateModel) {
return state.notifications;
}
@Selector([NotificationsState.getNotifications])
static getUnreadTotal(state: NotificationsStateModel, notifications: Notification[]) {
return notifications.reduce(() => ..., 0);
}
}
```
You might notice that the `getUnreadTotal` selector will have the notifications state injected as the first argument before accessing the notifications list.
This update has …
=> fix(store): do not inject container state by default

docs/advanced/action-handlers.md, docs/advanced/actions-life-cycle.md, docs/advanced/cancellation.md, docs/advanced/optimizing-selectors.md, docs/advanced/selector-utils.md, docs/concepts/select.md, docs/concepts/state.md, docs/concepts/store.md, docs/recipes/cache.md, docs/recipes/style-guide.md, docs/recipes/unit-testing.md
This commit updates the documentation to use selects as signals where possible, except for cases mentioned in the guide where selects may have both observables and signals. However, new users transitioning to NGXS are encouraged to work with the latest Angular features, which are signals.
=> docs: use new Angular features

docs/concepts/actions.md, docs/concepts/select.md
This commit completely updates the `select.md` to adopt a signal-first approach, as previously, all examples were based on observables. Most developers transitioning to NGXS would prefer to see examples using signals, as this concept is being heavily promoted by Angular.
Additionally, this commit removes examples using the `@Select` decorator since it's not usable and has critical issues due to its lack of integration with Angular's dependency injection.
Furthermore, the "special considerations" block has been removed, as the issues it addressed are no longer a concern.
=> docs: update `concepts/select.md`

packages/router-plugin/internals/src/symbols.ts, packages/storage-plugin/internals/src/symbols.ts, packages/storage-plugin/src/engines.ts, packages/storage-plugin/src/storage.plugin.ts, packages/store/internals/src/initial-state.ts, packages/store/internals/src/internal-tokens.ts, packages/store/plugins/src/symbols.ts, packages/store/src/decorators/action.ts, packages/store/src/decorators/selector/selector.ts, packages/store/src/decorators/state.ts, packages/store/src/dev-features/symbols.ts, packages/store/src/execution/dispatch-outside-zone-ngxs-execution-strategy.ts, packages/store/src/execution/symbols.ts, packages/store/src/internal/dispatcher.ts, packages/store/src/internal/internals.ts, packages/store/src/internal/lifecycle-state-manager.ts, packages/store/src/internal/state-factory.ts, packages/store/src/internal/state-operations.ts, packages/store/src/internal/state-operators.ts, packages/store/src/selectors/create-model-selector.ts, packages/store/src/selectors/create-pick-selector.ts, packages/store/src/selectors/create-property-selectors.ts, packages/store/src/standalone-features/initializers.ts, packages/store/src/symbols.ts, packages/websocket-plugin/src/symbols.ts
This commit updates all `ngDevMode` conditions to remove the check for `ngDevMode` being `undefined`. We can ensure it's always defined by Angular since VE has been dropped. However, the `typeof` check is still necessary to ensure code safety, as `ngDevMode` is a global variable provided by the framework.
=> refactor(store): rely on `ngDevMode` to be always defined

packages/store/src/decorators/selector/selector.ts, packages/store/src/private_api.ts, packages/store/src/selectors/create-property-selectors.ts, packages/store/src/selectors/create-selector.ts, packages/store/src/selectors/private_api.ts, packages/store/src/selectors/selector-checks.util.ts, packages/store/src/selectors/selector-types.util.ts, packages/store/types/tests/create-selector.lint.ts
This commit privately exports `ɵSelectorFunc`, `ɵStateSelector`, `ɵSelectorDef`, and `ɵSelectorReturnType`, as they might be utilized by developers working on advanced utilities who need access to these types externally. For example, they may create a function that accepts selector functions and returns signals with types corresponding to the return types of those selectors.
=> feat(store): export selector util types privately

docs/SUMMARY.md
Following a conversation with @arturovt, I'm opening a pull request to update the section headings. I've converted them all to uppercase.
=> docs: section headings as uppercase

packages/router-plugin/src/router.state.ts, packages/store/src/decorators/action.ts, packages/store/types/tests/action.lint.ts, packages/store/types/tests/dispatch.lint.ts
```
[ ] Bugfix
[X] Feature
```
The `@Action` decorator does not enforce that the actions passed to the decorator match the payloads expected by the method it decorates.
A simple example is the following—the below action has a payload `{ value: string }` but the handler expects `{ value: number }` incorrectly. This does not produce an error.
```
class ActionString {
static type = 'action1';
constructor(public value: string) {}
}
...
@Action(ActionString) …
```
=> feat(store): improve action decorator types

docs/recipes/waiting-for-app-stability.md
In this commit, we updated the "waiting for app stability" recipe to use
the experimental pending tasks service, which was publicly exposed in the
Angular API starting from version 18.
=> docs: update waiting for app stability recipe for Angular 18

docs/concepts/store/options.md
This commit updates the options section of the documentation to include information on generating environments because they are no longer present by default.
=> docs: update `options.md` to add a warning about environments

docs/recipes/unit-testing.md
In this commit, we updated the unit-testing recipe with a lot more useful information and code guides. We included the actions collector snippet, which has been successfully used in production apps for years and can be safely applied to external user apps.
=> docs: update unit-testing recipe

integration/app/app.component.html, integration/app/app.component.spec.ts, integration/app/app.component.ts, packages/store/internals/src/state-stream.ts, packages/store/tests/create-maps.spec.ts, packages/store/tests/issues/issue-2180-dispatching-in-effect.spec.ts, packages/store/tests/select-signal.spec.ts
In this commit, we decouple state signal updates from synchronous changes to adhere to constraints on updates inside effects. Situations may arise where actions are dispatched within effects, and if these actions are synchronous, the state signal would also receive synchronous updates. This can lead to an error indicating that signal writes are not permitted within effects.
Resolves #2180
=> fix(store): decouple state signal updates from synchronous changes

.bundlemonrc.integration.json, .github/actions/download-integration-test-artifacts/action.yml, .github/actions/setup/action.yml, .github/actions/upload-integration-test-artifact/action.yml, .github/workflows/pr-validation.yml, .github/workflows/release.yml, .github/workflows/trunk.yml
The saving of the cache was taking ages and the restoration of the cache was taking longer than the actual yarn install.
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> ci: skip cache for github actions

.bundlemonrc.integration.json, .bundlemonrc.json, .bundlemonrc.plugins.json
```
[ ] Bugfix
[ ] Feature
```
Bundlemon doesn't report on all built files
The file paths are correct, so that we report on all necessary files.
```
[ ] Yes
[x] No
```
=> ci: fix bundlemon reporting

CONTRIBUTING.md, README.md, docs/README.md, packages/store/README.md, publication/2023-03-20_announcing_ngxs_3_8/article.md, publication/2024-06-10_announcing_ngxs_18/article.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> docs: update discord link

packages/store/internals/testing/src/index.ts, packages/store/internals/testing/src/skip-console-logging.ts, packages/store/src/selectors/selector-checks.util.ts, packages/store/tests/selectors/create-model-selector.spec.ts, packages/store/tests/selectors/create-pick-selector.spec.ts, packages/store/tests/selectors/create-property-selectors.spec.ts
```
[x] Bugfix
[ ] Feature
```
The `createPropertySelectors` utility checks that the provided selector is a valid selector.
This is great, but if the utility is used within a state class it fails this check (during `ngDevMode`) because the `@State` decorator has not yet added the selector metadata.
A similar issue exists if a `@Selector` decorated selector is used within the same state class.
Issue Number: #2209
These usages are allowed. This was achieved by delaying …
=> fix: allow selector utils usage within state class

.bundlemonrc.json, CHANGELOG.md, packages/store/src/internal/lifecycle-state-manager.ts, packages/store/src/internal/state-context-factory.ts, packages/store/src/internal/state-factory.ts
In this commit, I'm working on optimizing how we handle action dispatches by avoiding repeated traversal of the `states` list. Instead, we prepare a map each time a new state is added, allowing us to perform O(1) lookups by action type in the future. This approach reduces complexity and improves performance.
I've tested it with benchmark.js, and here are the results:
```ts
class Increment {
static readonly type = 'Increment';
}
const states = Array.from({ length: 50 }).map((_, index) => {
@State({
name: `counter_${index + 1}`,
defaults: 0,
})
@Injectable()
class CounterState {
@Action(Increment)
increment(ctx: StateContext<number>) {
ctx.setState((counter) => counter + 1);
}
}
return CounterState;
});
```
```
store.dispatch() before changes x 3,435 ops/sec ±0.45% (65 runs sampled) …
```
=> perf(store): avoid going over states list every time action is dispatched

CHANGELOG.md, packages/store/src/plugin-manager.ts, packages/store/src/standalone-features/plugin.ts, packages/store/tests/issues/issue-2227-feature-plugins.spec.ts
In this commit, we add an inject function for the plugin manager to register child plugins.
The plugin manager supports parent-child functionality, allowing it to be initialized at
the child level.
Resolves #2227
=> fix(store): register feature plugins correctly

CHANGELOG.md, packages/store/internals/src/memoize.ts, packages/store/tests/issues/issue-2229-memoize-nan.spec.ts
In this commit, we update the memoize equality function to correctly check for `NaN`
values because we can't use the default `===` comparison operator, as `NaN` is not equal
to itself (`NaN === NaN` is false). Additionally, we have added a check using `Number.isNaN`.
=> fix(store): memoize selectors which return NaN

CHANGELOG.md, packages/logger-plugin/src/log-writer.ts, packages/logger-plugin/src/logger.plugin.ts, packages/logger-plugin/src/symbols.ts, packages/logger-plugin/tests/issues/filter-function-injection-context.spec.ts
In this commit, we wrap the `options.filter` function for the logger plugin to run within
the injection context, allowing the retrieval of any injectees that may have properties
required for filtering. For example, the user may want to skip logging actions until the
app's bootstrap is complete.
Additionally, the `isIE` check has been removed from the log writer, as Internet Explorer
is no longer supported by Angular.
=> fix(logger-plugin): run `filter` function in injection context

.bundlemonrc.json, CHANGELOG.md, packages/store/src/actions/action-registry.ts, packages/store/src/internal/state-factory.ts, packages/store/tests/helpers/promise-test-helper.ts, packages/store/tests/issues/canceling-promises.spec.ts
In this commit, we update the implementation of action invocation. The key addition is that
we now prevent writing to the state whenever an action handler is unsubscribed (completed or
cancelled). Since we have a "unique" state context object for each action being invoked, we
can set its `setState` and `patchState` functions to no-ops, essentially making them do
nothing when invoked.
=> fix(store): prevent writing to state once action handler is unsubscribed

CHANGELOG.md, packages/store/src/selectors/selector-utils.ts
`typeof` avoids prototype chain checks and type coercion, which is faster:
```
instanceof Function x 104,665,819 ops/sec ±4.90% (44 runs sampled)
typeof function x 169,867,932 ops/sec ±6.42% (55 runs sampled)
```
Btw fastest benchmarked checks were:
```js
1.
const returnValueType = typeof returnValue;
returnValueType[0] === 'f'
2.
const F_CHAR_CODE = 102;
const returnValueType = typeof returnValue;
(returnValueType.charCodeAt(0) ^ F_CHAR_CODE) === 0;
3.
const F_CHAR_CODE = 102;
const returnValueType = typeof returnValue;
returnValueType.charCodeAt(0) === F_CHAR_CODE;
```
=> perf(store): replace `instanceof Function` with `typeof`

CHANGELOG.md, packages/store/internals/src/memoize.ts
In this commit, we default to using `Object.is` as the equality check function (this function is also used by other frameworks). `Object.is` supports checking for `NaN` values internally. We have also removed the reset function, as it was unused. If needed in the future, it can be re-added.
=> refactor(store): use `Object.is` as default equality check

CHANGELOG.md, packages/router-plugin/src/router.state.ts
In this commit, we first remove the `@Selector()` decorator because we can use `createSelector` directly. This also removes `__decorate` calls for the `state` and `url` properties. Secondly, we mark these properties as 'pure.' The `/* @__PURE__ */` hint tells the bundler that `createSelector` has no side effects and that the output of this expression can be safely removed if unused. Therefore, if `state` or `url` is never accessed anywhere in our code, it can be tree-shaken.
=> refactor(router-plugin): mark selectors as pure

CHANGELOG.md, packages/storage-plugin/src/engines.ts
`new` expressions are considered side-effectful. The `/* @__PURE__ */` hint tells the bundler that `new InjectionToken` has no side effects and that the output of this expression can be safely removed if unused. Therefore, if `LOCAL_STORAGE_ENGINE` is never used, it can be dropped.
=> refactor(storage-plugin): mark engine tokens as pure

CHANGELOG.md, packages/store/internals/src/internal-tokens.ts, packages/store/src/internal/provide-internal-tokens.ts, packages/store/src/private_api.ts, packages/store/src/standalone-features/root-providers.ts
In this commit, we remove internal injection token providers from the root providers list. Instead, we expose a function that provides these tokens.
=> refactor(store): tree-shake internal state tokens

CHANGELOG.md, packages/websocket-plugin/src/websocket-handler.ts, packages/websocket-plugin/tests/websocket-handler-cleanup.spec.ts
Prevents dispatching `WebSocketDisconnected` action in `ngOnDestroy` hook of the `WebSocketHandler`. The `ngOnDestroy` hook is called after root injector has been destroyed, meaning that no dispatch stuff should be done.
=> fix(websocket-plugin): do not dispatch action when root injector is destroyed

CHANGELOG.md, packages/devtools-plugin/src/devtools.plugin.ts, packages/devtools-plugin/src/symbols.ts, packages/form-plugin/src/directive.ts, packages/router-plugin/src/router.state.ts, packages/storage-plugin/src/storage.plugin.ts, packages/store/src/actions-stream.ts, packages/store/src/dev-features/ngxs-unhandled-actions-logger.ts, packages/store/src/execution/dispatch-outside-zone-ngxs-execution-strategy.ts, packages/store/src/execution/internal-ngxs-execution-strategy.ts, packages/store/src/internal/dispatcher.ts, packages/store/src/internal/lifecycle-state-manager.ts, packages/store/src/internal/state-context-factory.ts, packages/store/src/internal/state-operations.ts, packages/store/src/store.ts, packages/websocket-plugin/src/websocket-handler.ts
In this commit, we remove constructor parameters to ensure compatibility with the `useDefineForClassFields` compiler option. When public class fields are enabled, such cases throw a `TS2729: Property used before its initialization` error. This occurs when a property (e.g., an injectee) is referenced before the constructor is executed.
Additionally, we are removing property decorators such as `@Inject` with this change. Property decorators are not permitted when experimental decorators are disabled. This adjustment helps make the framework compatible with these TypeScript compiler options moving forward.
=> refactor: use field initializers for injectees

CHANGELOG.md, packages/router-plugin/internals/src/symbols.ts, packages/storage-plugin/internals/src/symbols.ts, packages/storage-plugin/src/engines.ts, packages/storage-plugin/src/storage.plugin.ts, packages/storage-plugin/src/with-storage-feature.ts, packages/store/internals/src/initial-state.ts, packages/store/internals/src/internal-tokens.ts, packages/store/plugins/src/symbols.ts, packages/store/src/dev-features/symbols.ts, packages/store/src/execution/symbols.ts, packages/store/src/internal/internals.ts, packages/store/src/internal/lifecycle-state-manager.ts, packages/store/src/internal/state-factory.ts, packages/store/src/selectors/selector-utils.ts, packages/store/src/standalone-features/initializers.ts, packages/store/src/standalone-features/preboot.ts, packages/store/src/store.ts, packages/store/src/symbols.ts, packages/websocket-plugin/src/symbols.ts
In this commit, we're removing all const `NG_DEV_MODE` declarations and inlining `typeof ngDevMode !== 'undefined' && ngDevMode` conditions.
This change is **required** for ESBuild tree-shaking to work properly. It has been observed that development-only code is not being dropped in production builds.
For example, this code:
```js
const NG_DEV_MODE = typeof ngDevMode !== 'undefined' && ngDevMode;
if (NG_DEV_MODE) {
ensureStateNameIsValid(stateName);
}
```
Becomes the following after the build:
```js
var NG_DEV_MODE$4 = !1;
NG_DEV_MODE$4 && ensureStateNameIsValid(stateName);
```
Terser was able to inline `NG_DEV_MODE` variables, because it was able to evaluate their expressions during the build (that it's _falsy_) and remove them entirely.
=> refactor: allow tree-shaking of dev-only code

CHANGELOG.md, packages/store/src/dev-features/symbols.ts
Adds `__PURE__` annotation to the `NGXS_DEVELOPMENT_OPTIONS` to drop the code when it's unused in production.
=> refactor(store): tree-shake development options token

CHANGELOG.md, docs/concepts/store/meta-reducer.md, docs/plugins/README.md, packages/devtools-plugin/src/devtools.module.ts, packages/form-plugin/src/form.module.ts, packages/logger-plugin/src/logger.module.ts, packages/storage-plugin/src/storage.module.ts, packages/store/plugins/src/index.ts, packages/store/plugins/src/symbols.ts, packages/store/src/plugin-manager.ts, packages/store/src/standalone-features/plugin.ts, packages/store/src/standalone-features/root-providers.ts, packages/store/tests/plugins.spec.ts
We allow passing a plain function into `withNgxsPlugin`, as the plugin can be a simple
function (not a class).
=> fix(store): allow plain functions in `withNgxsPlugin`

CHANGELOG.md, packages/store/src/internal/state-factory.ts, packages/store/src/standalone-features/feature-providers.ts, packages/store/src/standalone-features/root-providers.ts
In this commit, we mark the state factory as a root provider to prevent its initialization
at feature levels when `provideStates` is called.
Previously, the state factory was initialized at feature levels because it needed to retrieve
the feature-level injector in order to call `injector.get(FeatureStateClass)`.
This was necessary because, when `NgxsModule.forFeature([BlogState])` was called, the `BlogState`
instance could only be retrieved from the feature injector hierarchy.
Now, since `addAndReturnDefaults` is called at the feature level inside the feature environment
initializer, it is executed within the feature injection context, allowing us to use the
`inject(...)` function directly.
=> perf(store): prevent initializing state factory at feature levels

CHANGELOG.md, packages/router-plugin/src/router.state.ts
Reverts https://github.com/ngxs/store/commit/699f0a0ed2f4b92281414ff0e0190590df072556.
=> fix(router-state): revert router state changes

CHANGELOG.md, packages/store/src/standalone-features/initializers.ts, packages/store/src/standalone-features/root-guard.ts, packages/store/tests/issues/issue-2277-provide-store-twice.spec.ts
In this commit, we are adding the root store initializer guard, which ensures that
`provideStore()` is not accidentally called multiple times (e.g., in feature-level
providers such as route providers).
=> fix(store): add root store initializer guard

CHANGELOG.md, packages/store/internals/src/state-stream.ts, packages/store/src/actions-stream.ts, packages/store/src/internal/action-results.ts, packages/store/src/internal/dispatcher.ts, packages/store/src/internal/state-factory.ts
We complete the `InternalDispatchedActionResults` once the application is destroyed to ensure there are no active subscribers after resources have been cleaned up.
=> fix(store): complete action results on destroy

CHANGELOG.md, packages/form-plugin/src/directive.ts
In this commit, we replace `takeUntil` with `takeUntilDestroyed` and remove `ngOnDestroy`
in favor of using `DestroyRef`.
=> refactor(form-plugin): replace `takeUntil` with `takeUntilDestroyed`

.bundlemonrc.json, CHANGELOG.md, packages/store/src/pending-tasks.ts, packages/store/tests/issues/pending-task-notifications.spec.ts
An `INFINITE_CHANGE_DETECTION` error has been logged to the error service multiple times,
occurring randomly depending on the number of actions dispatched in a row. This happens
because a pending task is added every time an action is dispatched. Removing a pending task
via the public API forces a scheduled tick, ensuring that stability is asynchronous and
delayed until there has been at least an opportunity to run app synchronization.
This change reduces the number of change detection cycles. For example, if 10 synchronous
actions are dispatched in a row, it may previously trigger 10 change detection cycles, as
tasks would be removed 10 times.
We listen to the actions stream, and every time a context with a `dispatched` status is
generated, we add a pending task only once and keep it …
=> fix(store): reduce change detection cycles with pending tasks

CHANGELOG.md, packages/store/src/actions-stream.ts
We complete the `dispatched$` subject within the internal actions once the application is destroyed
to ensure there are no active subscribers after resources have been cleaned up.
=> fix(store): complete `dispatched$` in internal actions

CHANGELOG.md, packages/store/src/execution/dispatch-outside-zone-ngxs-execution-strategy.ts, packages/store/src/symbols.ts
In this commit, we replace `isPlatformServer` in the store with the new built-in variable
`ngServerMode`, available starting from Angular 19.
This compile-time variable allows the code to be tree-shakable.
=> build(store): use `ngServerMode` to check whether we are in SSR

CHANGELOG.md, packages/storage-plugin/src/engines.ts, packages/storage-plugin/src/internals.ts, packages/storage-plugin/src/storage.module.ts, packages/storage-plugin/src/storage.plugin.ts
In this commit, we replace `isPlatformServer` in the storage plugin with the new built-in variable
`ngServerMode`, available starting from Angular 19.
This compile-time variable allows the code to be tree-shakable.
=> build(storage-plugin): use `ngServerMode` to check whether we are in SSR

CHANGELOG.md, packages/router-plugin/src/router.state.ts
In this commit, we only unsubscribe from `router.events`. The `Store` is automatically completed by NGXS when the root injector is destroyed; therefore, we remove the replay subject and the `takeUntil` dependency.
=> refactor(router-plugin): reduce RxJS depedency

CHANGELOG.md, packages/hmr-plugin/src/internal/hmr-lifecycle.ts, packages/store/internals/src/ngxs-app-bootstrapped-state.ts, packages/store/src/internal/lifecycle-state-manager.ts, packages/websocket-plugin/src/websocket-handler.ts, packages/websocket-plugin/tests/websocket-handler-cleanup.spec.ts
In this commit, we reduce the usage of RxJS utilities as they may be redundant. For example,
we replace the replay subject with a behavior subject and remove some unnecessary operators.
=> refactor: reduce RxJS dependency

CHANGELOG.md, integration/app/list/list.component.ts, packages/router-plugin/src/router.state.ts, packages/router-plugin/tests/issues/issue-1407.spec.ts, packages/router-plugin/tests/issues/issue-1718-url-recognition.spec.ts, packages/router-plugin/tests/router-data-resolved.spec.ts, packages/router-plugin/tests/router.plugin.spec.ts
In this commit, we switch from using the selector decorator to allow it to be dropped in production
for apps that don't use it at all.
Breaking change: To get the `RouterState.state`, it is now required to call the `state`
function — `select(RouterState.state())`. Previously, it was possible to provide a generic type for
the router state, e.g., `select(RouterState.state<CustomRouterState>)`, but this is not possible
if `state` were a property.
=> refactor(router-state): change `@Selector` to `createSelector`

.circleci/config.yml
```
[ ] Bugfix
[ ] Feature
```
Updated the browser-tools CircleCI orb to latest.
```
[ ] Yes
[x] No
```
-----
<a href="https://stackblitz.com/~/github.com/ngxs/store/tree/markwhitfeld/ci-update-circleci-browser-tools-to-latest"><img src="https://developer.stackblitz.com/img/review_pr_small.svg" alt="Review PR in StackBlitz" align="left" width="103" height="20"></a> _Submitted with [StackBlitz](https://stackblitz.com/~/github.com/ngxs/store/tree/markwhitfeld/ci-update-ci …
=> ci: update circleci browsers orb to latest

CHANGELOG.md, packages/store/src/pending-tasks.ts
Stop contributing to stability once the application has become stable, which may happen
on the server before the platform is destroyed or in the browser once hydration is complete.
=> fix(store): stop contributing to stability once app is stable

README.md, docs/SUMMARY.md, docs/community-and-labs/community/developer-guide.md
```
[ ] Bugfix
[ ] Feature
```
This PR improves the NGXS Developer Guide by refining structure, improving readability, and ensuring accuracy in testing commands. The changes include:
- Refined structure and readability of the local development guide.
- Improved formatting for installation and contribution steps.
- Make the Developer Guide accessible on the documentation site
- Corrected the `yarn test:ci` command to `yarn test`.
```
[ ] Yes
[x] No
``` …
=> docs(app): improve developer guides for local development

CHANGELOG.md, packages/store/internals/src/index.ts, packages/store/internals/src/rxjs.ts, packages/store/src/actions-stream.ts, packages/store/src/internal/dispatcher.ts, packages/store/src/internal/lifecycle-state-manager.ts, packages/store/src/internal/state-factory.ts, packages/store/src/store.ts
In this commit, we reduce the number of imported symbols from RxJS by removing the `pairwise()`
operator (since users consuming the NGXS library may not use it) and replacing RxJS `of()`
with a custom function that instantly returns an observable.
=> refactor(store): pull less RxJS symbols

CHANGELOG.md, packages/storage-plugin/src/with-storage-feature.ts, packages/store/src/standalone-features/initializers.ts, packages/store/src/standalone-features/plugin.ts
The `ENVIRONMENT_INITIALIZER` is unavailable in newer Angular versions.
=> refactor: replace `ENVIRONMENT_INITIALIZER`

packages/store/internals/src/action-registry.ts, packages/store/internals/src/index.ts, packages/store/src/internal/state-factory.ts
In this commit, we move the registry from the core to the internals package to prepare for attaching action functionality.
=> refactor(store): move registry to internals

CHANGELOG.md, packages/store/src/internal/dispatcher.ts
Adds a defensive check in the `compose` helper to ensure that no state
functions are executed once the root `Injector` has been destroyed.
Although the `destroyed` flag on `Injector` is not part of the public API,
it is available on the root injector instance. Using a cast here avoids the
need to inject `ApplicationRef`, which could introduce cyclic dependencies
or breaking changes.
This prevents runtime errors and unintended behavior when actions are
dispatched or state pipelines are invoked after application teardown.
=> fix(store): guard against running state functions after injector is destroyed

CHANGELOG.md, packages/storage-plugin/src/storage.plugin.ts
Switched from a closure-returning `actionMatcher` function to a direct type comparison approach. This removes the intermediate function allocation and makes the intent clearer by directly checking `getActionTypeFromInstance(event)` against known action types (`InitState.type` and `UpdateState.type`).
=> perf(storage-plugin): replace closure-based action matcher with direct type comparison

CHANGELOG.md, packages/router-plugin/src/router.state.ts
Previously, the router plugin always patched NGXS state on every router event, even if the new router snapshot was identical to the current one. This caused unnecessary updates to the internal NGXS state signal, triggering recomputations of `selectSignal` selectors and extra Angular change detection cycles.
With this change, we now compare the current and incoming router state (trigger, navigationId, and serialized snapshot). If they are equal, the state update is skipped. This avoids redundant signal emissions, leading to fewer recomputations and improved performance in large apps.
=> fix(router-plugin): avoid redundant NGXS state updates for identical router snapshots
